### ISSUE TITLE
Debian repo signing key not on keyserver

### ISSUE THREAD

**Issue by SebastianS90** [hanzz/spectrum2#102]
Thanks for providing the jessie packages (c.f. #70)
The signing key E01FC4111AFDEA51 is not available on the keyservers, such that the import described [here](http://spectrum.im/documentation/installation/packages_debian_ubuntu.html) fails. Without the key, aptitude gives some nasty warnings prior to installing the packages.

Solution: Upload public key E01FC4111AFDEA51 to the keyservers.

**Comment by vitalyster** [comment]
Key definitely on the server, but sometimes failed to download due to connectivity problems, maybe better just upload key to our server

**Comment by SebastianS90** [comment]
Neither https://sks-keyservers.net/pks/lookup?op=vindex&search=1AFDEA51 nor https://sks-keyservers.net/pks/lookup?op=vindex&search=E01FC4111AFDEA51 show a result to me at the moment. And I guess that apt/gpg will query the same database when you specify `--keyserver hkp://pool.sks-keyservers.net --recv-keys 1AFDEA51` as shown the docs.

**Comment by vitalyster** [comment]
$ gpg --search-keys --keyserver hkp://pool.sks-keyservers.net 1AFDEA51
gpg: searching for "1AFDEA51" from hkp server pool.sks-keyservers.net
(1)     Vitaly Takmazov <vitalyster@gmail.com>
          2048 bit RSA key 1AFDEA51, created: 2015-01-07

**Comment by SebastianS90** [comment]
Hmm ok strange. After trying it several times I managed to download the key from their server via commandline, even though it's not available in sks-keyservers.net webinterface. Closing this here as it's not a problem of spectrum2, rather a problem with the keyserver. Thanks for the help!
