### ISSUE TITLE
Cant compile it on debian wheezy (x64)

### ISSUE THREAD

**Issue by TomTheDragon** [hanzz/spectrum2#104]
I did try to follow this little guide over here http://spectrum.im/documentation/installation/packages_debian_ubuntu.html and i did manage to compile libcommuni but i just get an error if i try to compile spectrum2.

In file included from /usr/include/boost/thread/pthread/mutex.hpp:14:0,
                 from /usr/include/boost/thread/mutex.hpp:16,
                 from /usr/include/boost/thread/pthread/thread_data.hpp:12,
                 from /usr/include/boost/thread/thread.hpp:17,
                 from /usr/include/Swiften/Network/BoostIOServiceThread.h:10,
                 from /tmp/spectrum2-2.0.1/include/transport/Transport.h:26,
                 from /tmp/spectrum2-2.0.1/libtransport/UsersReconnecter.cpp:23:
/usr/include/boost/thread/xtime.hpp:23:5: error: expected identifier before numeric constant
/usr/include/boost/thread/xtime.hpp:23:5: error: expected ‘}’ before numeric constant
/usr/include/boost/thread/xtime.hpp:23:5: error: expected unqualified-id before numeric constant
/usr/include/boost/thread/xtime.hpp:46:14: error: expected type-specifier before ‘system_time’
In file included from /usr/include/boost/thread/pthread/mutex.hpp:14:0,
                 from /usr/include/boost/thread/mutex.hpp:16,
                 from /usr/include/boost/thread/pthread/thread_data.hpp:12,
                 from /usr/include/boost/thread/thread.hpp:17,
                 from /usr/include/Swiften/Network/BoostIOServiceThread.h:10,
                 from /tmp/spectrum2-2.0.1/include/transport/Transport.h:26,
                 from /tmp/spectrum2-2.0.1/libtransport/UsersReconnecter.cpp:23:
/usr/include/boost/thread/xtime.hpp: In function ‘int xtime_get(xtime*, int)’:
/usr/include/boost/thread/xtime.hpp:73:40: error: ‘get_system_time’ was not declared in this scope
/usr/include/boost/thread/xtime.hpp:73:40: note: suggested alternative:
In file included from /usr/include/boost/thread/locks.hpp:12:0,
                 from /usr/include/boost/thread/pthread/mutex.hpp:12,
                 from /usr/include/boost/thread/mutex.hpp:16,
                 from /usr/include/boost/thread/pthread/thread_data.hpp:12,
                 from /usr/include/boost/thread/thread.hpp:17,
                 from /usr/include/Swiften/Network/BoostIOServiceThread.h:10,
                 from /tmp/spectrum2-2.0.1/include/transport/Transport.h:26,
                 from /tmp/spectrum2-2.0.1/libtransport/UsersReconnecter.cpp:23:
/usr/include/boost/thread/thread_time.hpp:19:24: note:   ‘boost::get_system_time’
In file included from /usr/include/boost/thread/pthread/mutex.hpp:14:0,
                 from /usr/include/boost/thread/mutex.hpp:16,
                 from /usr/include/boost/thread/pthread/thread_data.hpp:12,
                 from /usr/include/boost/thread/thread.hpp:17,
                 from /usr/include/Swiften/Network/BoostIOServiceThread.h:10,
                 from /tmp/spectrum2-2.0.1/include/transport/Transport.h:26,
                 from /tmp/spectrum2-2.0.1/libtransport/UsersReconnecter.cpp:23:
/usr/include/boost/thread/xtime.hpp: At global scope:
/usr/include/boost/thread/xtime.hpp:88:1: error: expected declaration before ‘}’ token
make[3]: *** [libtransport/CMakeFiles/transport.dir/UsersReconnecter.cpp.o] Error 1
make[3]: Leaving directory `/tmp/spectrum2-2.0.1'
make[2]: *** [libtransport/CMakeFiles/transport.dir/all] Error 2
make[2]: Leaving directory `/tmp/spectrum2-2.0.1'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/tmp/spectrum2-2.0.1'
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

**Comment by hanzz** [comment]
This is bug in boost in your distribution, we cannot do anything about that:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=729584

For more info, you can google:

/usr/include/boost/thread/xtime.hpp:23:5: error: expected identifier before numeric constant

**Comment by vitalyster** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=703980 - this bugreport says the problem with old boost and newer libc, maybe you need downgrade to libc shipped with wheezy (or check updates, since that report marked as resolved in 1.49.0-4 package)
