### ISSUE TITLE
libpurple: Support for PURPLE_MESSAGE_IMAGES

### ISSUE THREAD

**Issue by Ghabry** [hanzz/spectrum2#106]
Many plugins for libpurple, e.g. facebook, skype and telegram fetch the images when they receive them and send them with option PURPLE_MESSAGE_IMAGES. In Pidgin this will show the embedded image in the chat window but this of course doesn't work for spectrum2. Spectrum2 just silently ignores these messages.

Possible solutions:
XEP-0231. That one looks super useful. Problem: Almost no client supports this :(
OR
Start a file transfer: Could be annoying when each sticker in FB generates a transfer.
OR
Download the file in some static spectrum2 directory that is reachable from a web browser and send the spectrum2 user a link.

**Comment by thundergreen** [comment]
I agree with the third possibility :)

**Comment by vitalyster** [comment]
I'm voting for XEP-0060 with fallback to 3)

**Comment by rigid** [comment]
@hanzz :+1: for your option.
although anything is better than nothing here...

**Comment by hanzz** [comment]
Just some implementation details for this bug. We have to check the message from libpurple for `<img id="foo">` or `<img id='bar'>`, fetch the image from imgstore and store it, remove the `id` and use the right `src` to point to the right image. Then generate plaintext part of the message to replace img with a link and xhtml-im part of the message with the image.

**Comment by kousu** [comment]
I need to hijack this thread for a moment: does Spectrum still work with Facebook? How is that possible? I have libpurple 2.10.12-1 under my Pidgin and it fails at login with:

```
<features xmlns='http://etherx.jabber.org/streams'>
	<starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'/>
	<mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>
		<mechanism>X-FACEBOOK-PLATFORM</mechanism>
		<mechanism>PLAIN</mechanism>
	</mechanisms>
</features>
<starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'/>
<proceed xmlns='urn:ietf:params:xml:ns:xmpp-tls'/>
<features xmlns='http://etherx.jabber.org/streams'>
	<mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>
		<mechanism>X-FACEBOOK-PLATFORM</mechanism>
		<mechanism>PLAIN</mechanism>
	</mechanisms>
</features>
<auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='PLAIN' client-uses-full-bind-result='true'>XXXXXXXXXXXXXXXXXXXXXXXXXX=</auth>
<failure xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>
	<not-authorized/>
	<text>plain login failed</text>
</failure>
```

I thought Facebook turned off XMPP in favour of Messenger four months ago, but you say you just tested this this week.  Is Spectrum using a secretly updated libpurple?

**Comment by vitalyster** [comment]
Spectrum uses prpl-facebook

**Comment by kousu** [comment]
That's https://github.com/jgeboski/purple-facebook? Thank you for the clue, and for fighting the walled gardening.
