### ISSUE TITLE
libpurple backend: MUC Topics

### ISSUE THREAD

**Issue by rigid** [hanzz/spectrum2#107]
MUC topics are not shown & never transferred. Instead a userlist is shown, which is not optimal for multiple rooms with the same participants.
Please use the Topic as MUC name and JID as fallback.
Please handle topic-changed signals and forward topic to frontend.
Also, the description field in MUC DISCO requests doesn't contain the topic (but the JID of the room)

**Comment by rigid** [comment]
Please reopen. The topic is still not forwarded as it seems. (grep topicword backend.log or spectrum2.log doesn't show anything)

**Comment by hanzz** [comment]
Where do ou don't see the topic? If you join the room, you should see the topic in that room. In the XMPP world, it's called "subject", so please grep "subject" in the log.

Also, what network and room are you trying to connect?

**Comment by rigid** [comment]
there's no topic at all. grep for "subject" in spectrum2.log also doesn't give anything.

i'm connecting to skype (purple-skypeweb) and join several groupchats.
