### ISSUE TITLE
Failed getting Magic T value

### ISSUE THREAD

**Issue by nahuelange** [hanzz/spectrum2#119]
Hi,

After install (on debian jessie) of spectrum and configuring the transport, and configuring my user I got this error:
```
Failed getting Magic T value
```
Any idea why ?
I use prpl-skypeweb backend

**Comment by vitalyster** [comment]
Errors found in backend-*.log are backend errors, in this case it is prpl-skypeweb error https://github.com/EionRobb/skype4pidgin/issues/297
