### ISSUE TITLE
How to join channels over the swiften backend?

### ISSUE THREAD

**Issue by TomTheDragon** [hanzz/spectrum2#123]
I already tried many combinations and this one finally did list the channels of the external xmpp server.

conference.externalserver.com@xmpp.serverwithspectrum.com

But i still cant join the channels, it just gives me an error message.

**Comment by vitalyster** [comment]
conference%externalserver.com@...

**Comment by TomTheDragon** [comment]
I tried this one and it dont even list any channels.

**Comment by vitalyster** [comment]
please show backend log

**Comment by TomTheDragon** [comment]
OK i got it working with "channel%conference.externalserver.com@xmpp.serverwithspectrum.com".

But it is a bit confusing because when i search in "conference.externalserver.com@xmpp.serverwithspectrum.com" to get the channel list and i try to join one, it then simply trys to connect to "channel@conference.externalserver.com".

Would it be possible that "%conference.externalserver.com" could be added behind every channel in the channel list?

**Comment by vitalyster** [comment]
Good XMPP client should escape @ with \40 and join as is

**Comment by TomTheDragon** [comment]
I tested this with Pidgin, Miranda, Gajim, PSI+ and its always the same. I mean it connects if i modify the channel name again but its really a bit annoying to do.

**Comment by vitalyster** [comment]
Just add them to bookmarks, most of clients are support it
