### ISSUE TITLE
Joining chatroom with skype4pidgin backend

### ISSUE THREAD

**Issue by nahuelange** [hanzz/spectrum2#124]
Hi,
Is there a way to join a chatroom through the skype4pidgin backend?

**Comment by pztrn** [comment]
Browse for conferences on transport domain (e.g. skype.example.com).

**Comment by nahuelange** [comment]
I can't see any chatroom in the conference list of transport domain… But in web.skype.com I can see I'm in.
Maybe there is a way to force joining it, but how ?

**Comment by nahuelange** [comment]
Nevermind, I had to reconnect, and it worked !
Thanks
