### ISSUE TITLE
cannot start spectrum2 on Debian

### ISSUE THREAD

**Issue by masscream** [hanzz/spectrum2#127]
Hello, I successfully compiled & installed Spectrum2 on Debian, however when I try to run its manager it gives me following error:

spectrum2_manager: error while loading shared libraries: libtransport.so.2.0: cannot open shared object file: No such file or directory

root@server:/etc/spectrum2# find / -name libtransport.so.2.0
/root/libtransport/libtransport/libtransport.so.2.0
/usr/local/lib/libtransport.so.2.0

But when I execute the search command I can find that file. Is it a configuration issue or will I have to recompile it with some other dependencies? Thanks

**Comment by vitalyster** [comment]
1) `/usr/local/lib` is not in your `LD_LIBRARY_PATH`
2) use packaging scripts
