### ISSUE TITLE
Whatsapp support?

### ISSUE THREAD

**Issue by yniwly43** [hanzz/spectrum2#130]
Hi there,

Was the Whatsapp support removed?

**Comment by thundergreen** [comment]
I think as yowsup is not working properly ATM every help with transwhat is freezed

**Comment by vitalyster** [comment]
If you are talking about public Slack gateway, there was always only IRC gateway, but you can run self-hosted instance with any supported "backend", and there is a whatsapp backend. Note, whatsapp support is unstable and you can get banned by Facebook for using third-party client.

**Comment by thundergreen** [comment]
This is wip and ATM no update yet. Yowsup is working on this.we will se the
next month

Thorsten Fröhlich
Am 27.04.2016 08:52 schrieb "vitalyster" <notifications@github.com>:

**Comment by yniwly43** [comment]
Do you have any updates from Yowsup themselves? Because I am not sure anyone is working on this, truly..

**Comment by thundergreen** [comment]
Just follow the github issue tracker. They are working on it but there's no actual save version atm 

https://github.com/tgalal/yowsup
https://github.com/jlguardi/yowsup

**Comment by yniwly43** [comment]
I doubt there will be, this is probably a server change.

**Comment by rigid** [comment]
feel free to give my fork of transwhat a try: https://github.com/rigid/transwhat
The develop branch works with yowsups current develop branch (was wa16 before)
while quick and probably still not complete, it works for me. I sent a PR to merge it.

**Comment by thundergreen** [comment]
Please describe what exactly works your setup and config thatbwe all have
the same to verify ;)

Thorsten Fröhlich
Am 27.04.2016 23:34 schrieb "rigid" <notifications@github.com>:
