### ISSUE TITLE
need help with docker image

### ISSUE THREAD

**Issue by strannick-ru** [hanzz/spectrum2#131]
Hello.

I try to use docker image on same host where ejabberd running.
Docker want start, becouse port 5222 is busy (ejabberd use it).

Please, show me right way to use Spectrum2 docker image and Ejabberd on same host.

**Comment by vitalyster** [comment]
put `server_mode=0` in configuration to start spectrum in "gateway mode" (on 5347 port)

**Comment by strannick-ru** [comment]
my config:
```
[service]
frontend=xmpp
server_mode=0
jid = icq.rokiroki.ru
password = LaGrandeSecret0!
server = 192.168.100.10
port = 5349
backend_host = 127.0.0.1
users_per_backend=10
backend=/usr/bin/spectrum2_libpurple_backend
protocol=prpl-icq

[identity]
name=ICQ Transport
type=icq

[logging]
config = /etc/spectrum2/logging.cfg
backend_config = /etc/spectrum2/backend-logging.cfg

[database]
type = sqlite3
database = /var/lib/spectrum2/$jid/icq-purple_transport.sql

[registration]
enable_public_registration=1
```
I start it and see it:
```
docker run --name="spectrum2" -d -p 5222:5222 -v /opt/spectrum2/configuration:/etc/spectrum2/transports -v /opt/spectrum2/data:/var/lib/spectrum2 spectrum2/spectrum2 
91a39a8ce9a3586e2d63db0b5cb63125962fa4e4331cfb5ab0f23dc1407c5c7b
docker: Error response from daemon: driver failed programming external connectivity on endpoint spectrum2 (5d3b3ef59b3335560a3ad43132f475274f46658f951796dc4bf32d7cbd8b2ed7): Error starting userland proxy: listen tcp 0.0.0.0:5222: bind: address already in use.
```

**Comment by vitalyster** [comment]
You have 5349 port in configuration, but trying to expose 5222 port from command line.

**Comment by vitalyster** [comment]
btw, in gateway mode you no need to expose any ports

**Comment by strannick-ru** [comment]
hmm. Try to start docker without expose ports
see in logs:
`2016-04-28 12:46:31,169 INFO  XMPPFrontend: Connecting XMPP server 192.168.100.10 port 5349`

tried use
`server = 127.0.0.1`
in config, same result

**Comment by vitalyster** [comment]
You should configure network(firewall?) access  to `192.168.100.10` from docker network interface, check the docker docs

**Comment by vitalyster** [comment]
Feel free to reopen if problem not solved
