### ISSUE TITLE
Unable to run Spectrum2 for any protocol

### ISSUE THREAD

**Issue by genesis231** [hanzz/spectrum2#138]
Log Report : - /var/log/spectrum2/spectrum2.log

2016-05-04 19:55:35,858 ERROR NetworkPluginServer: Backend can not be started, exit_code=2, possible error: No such file or directory
2016-05-04 19:55:35,858 ERROR NetworkPluginServer: This usually means the path to backend executable defined in config file as '[service] backend="..."' is wrong or the executable does not exists.
2016-05-04 19:55:35,858 ERROR NetworkPluginServer: Check backend log for more details
2016-05-04 19:55:35,858 INFO  NetworkPluginServer: Starting new backend /usr/bin/spectrum2_libpurple_backend --host 127.0.0.1 --port 34187 --service.backend_id=1 "-j" "whatsapp.xmpp" "/etc/spectrum2/transports/whatsapp.cfg" 
2016-05-04 19:55:35,859 INFO  NetworkPluginServer: Tried to spawn first backend with pid 9555
2016-05-04 19:55:35,859 INFO  NetworkPluginServer: Backend should now connect to Spectrum2 instance. Spectrum2 won't accept any connection

**Comment by vitalyster** [comment]
```
 the path to backend executable defined in config file as '[service] backend="..."' is wrong or the executable does not exists
```
It is the root problem

**Comment by genesis231** [comment]
Correct if i m wrong


[service]
# The name of user/group Spectrum runs as.
#user=spectrum
#group=spectrum

# JID of Spectrum instance.
server_mode= 0
#here tester2.chickenkiller.com 
jid = facebook.tester2.chickenkiller.com

# Password used to connect the XMPP server.
password = secret

# XMPP server to which Spectrum connects in gateway mode.
server = 127.0.0.1

# XMPP server por
port = 5347

# Interface on which Spectrum listens for backends.
backend_host = 127.0.0.1

# Port on which Spectrum listens for backends.
# By default Spectrum chooses random backend port and there's
# no need to change it normally
backend_port=10001

# Number of users per one legacy network backend.
users_per_backend=10
# For Skype - must be =1
#users_per_backend=1

# Full path to backend binary.
backend= /usr/bin/spectrum2_libpurple_backend
#backend=/usr/bin/spectrum2_libcommuni_backend
# For skype:
#backend=/usr/bin/xvfb-run -a -s "-screen 0 10x10x8" -f /tmp/x-skype-gw /usr/bin/spectrum2_skype_backend
# For skype if instance drops privileges (`user`/`group` options) we should set writable HOME folder for D-BUS:
#backend=/usr/bin/env HOME=/var/lib/spectrum2 xvfb-run -a -s "-screen 0 10x10x8" -f /tmp/x-skype-gw /usr/bin/spectrum2_skype_backend

# Libpurple protocol-id for spectrum_libpurple_backend
protocol=prpl-facebook
#protocol=prpl-msn
#protocol=prpl-icq

# protocol=any means that user sets his protocol in his JID which has to be
# in following format: protocol.username@domain.tld
# So for example: prpl-jabber.hanzz.k%gmail.com@domain.tld
#protocol=any

[identity]
# Name of Spectrum instance in service discovery
name=Spectrum Facebook Transport

# Type of transport ("msn", "icq", "xmpp").
# Check http://xmpp.org/registrar/disco-categories.html#gateway
type=facebook

# Category of transport, default is "gateway
#category=gateway

[logging]
# log4cxx/log4j logging configuration file in ini format used for main spectrum2 instance.
config = /etc/spectrum2/logging.cfg

# log4cxx/log4j logging configuration file in ini format used for backends.
backend_config = /etc/spectrum2/backend-logging.cfg

[database]
# Database backend type
# "sqlite3", "mysql", "pqxx", or "none" without database backend
type = mysql

# For SQLite3: Full path to database
# For MySQL and PostgreSQL: name of database
# default database = /var/lib/spectrum2/$jid/database.sql
database = facebook

# Server.
server = localhost

# Port.
port = 3306

# User.
user = root

# Paasword.
password = ****@root

# Prefix used for tables
prefix = facebook__

# Connection string (for pqxx only!)
# If you set this, it ignores every other database option except for type and prefix.
#connectionstring = host=localhost user=specturm password=secret

[registration]
# Enable public registrations
enable_public_registration=1

# Text to display upon user registration form
username_label=Jabber JID (e.g. user@server.tld):
instructions=Enter your remote jabber JID and password as well as your local username and password
username_mask=$username@chat.facebook.com
# If True a local jabber account on <local_account_server> is needed
# for transport registration, the idea is to enable public registration
# from other servers, but only for users, who have already local accounts
#require_local_account=1
#local_username_label=Local username (without @server.tld):
#local_account_server=localhost
#local_account_server_timeout=10000

**Comment by genesis231** [comment]
Correct me, if i m wrong.

[service]
frontend=xmpp
server_mode=0
jid = whatsapp.xmpp
password = my_password
server = 127.0.0.1
port = 5349
backend_host = 127.0.0.1
users_per_backend=10
backend=/usr/bin/spectrum2_libpurple_backend
protocol=prpl-whatsapp

[identity]
name=Whatsapp Transport
type=whatsapp

[logging]
config = /etc/spectrum2/logging.cfg
backend_config = /etc/spectrum2/backend-logging.cfg

[database]
type = sqlite3
database = /var/lib/spectrum2/$jid/whatsap-purple_transport.sql

[registration]
enable_public_registration=1

**Comment by thundergreen** [comment]
@genesis231 sure
```
backend=/usr/bin/spectrum2_libpurple_backend

```

is not 
```
backend=/usr/local/bin/spectrum2_libpurple_backend
```

try: whereis spectrum2 in the shell :)

**Comment by genesis231** [comment]
Solved. Thanks @thundergreen  :)

**Comment by thundergreen** [comment]
@genesis231 keep me posted if purple WhatsApp works for u please

Thorsten Fröhlich
Am 04.05.2016 17:39 schrieb "genesis231" <notifications@github.com>:

**Comment by genesis231** [comment]
@thundergreen accept my invitation on gtalk. sent@thundergreen@gmail.com

**Comment by thundergreen** [comment]
@genesis231 just add me in jabber:

thorsten@emevth.no-ip.biz

**Comment by thundergreen** [comment]
Accepted!

Thorsten Fröhlich
Am 05.05.2016 15:30 schrieb "genesis231" <notifications@github.com>:
