### ISSUE TITLE
Can't load configuration file.

### ISSUE THREAD

**Issue by budkin** [hanzz/spectrum2#140]
I'm running Debian 8, and trying to launch spectrum with prosody in gateway mode via `sudo spectrum2_manage start` and it says "Can't load configuration file". It doesn't produce any logs, at least I couldn't find any
my config is in the link
http://pastebin.com/5fzGC76U

**Comment by vitalyster** [comment]
You are miss `spectrum2_manager.cfg`

**Comment by budkin** [comment]
You should probably add some information about that file here [http://spectrum.im/documentation/tutorials/gateway_mode.html](url)
