### ISSUE TITLE
Telegram-purple plugin not showing Groups

### ISSUE THREAD

**Issue by PelNet** [hanzz/spectrum2#142]
The telegram-purple plugin for Spectrum2 is working but no Telegram Groups can be found by means of service discovery. 

Tested in Gateway mode.
Spectrum2 version: 2147-1862908

**Comment by vitalyster** [comment]
Seems like it is telegram-purple plugin issue, because I did not see my groups in finch. Tested with telegram purple master (and dev-1.3.0 just crashed at login)
