### ISSUE TITLE
unable to install on Centos   "Not Working"

### ISSUE THREAD

**Issue by IshwarChandra** [hanzz/spectrum2#148]
HI, 
I am trying to install Spectrum2 using this URL and it's not working. Could anyone please check this and let me know if it's working fine?

URL I am using- 
http://spectrum.im/documentation/installation/fedora_rhel.html

**Comment by vitalyster** [comment]
define "not working" please

**Comment by vitalyster** [comment]
http://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by IshwarChandra** [comment]
Hi vitalyster,

For better understanding I am attaching snapshot here. I might not be able to explain better as I am new to Linux world as well github. 
So please look at Snapshot and help me out.
![download](https://cloud.githubusercontent.com/assets/2242506/15668649/01a92776-273a-11e6-9378-a66a19c8e7f5.png)

**Comment by vitalyster** [comment]
You didn't add mcepl-spectrum2 repo to your repo list. Also make sure you have centos 7 x86_64

**Comment by IshwarChandra** [comment]
Thanks, it worked.
