### ISSUE TITLE
what different build with git clone and source code file ???

### ISSUE THREAD

**Issue by noob2020** [hanzz/spectrum2#153]
first sorry if my english is not good

i tried compile spectrum  with git clone  telegram is not work (hangouts, facebook, twitter, skypeweb work) but if i compile spectrum with sourcecode file tar.gz hangouts is not work (telegram, facebook, twitter, skypeweb work)

**Comment by vitalyster** [comment]
Please give exact link to tar.gz which you are using

**Comment by noob2020** [comment]
https://github.com/hanzz/spectrum2/archive/2.0.3.tar.gz..

**Comment by vitalyster** [comment]
2.0.3 is the current released version, it doesn't have hangouts support yet, which was added later and you are using it when cloning development tree. But current development tree have some issues, so yes, it's known issue
