### ISSUE TITLE
Unable to connect to Skype 

### ISSUE THREAD

**Issue by teamu** [hanzz/spectrum2#155]
We are using Openfire+Gojara Plugin+Spark and Spectrum to connect with Skype.  

Gojara shows the stats of Spectrum2 but we are still facing issue in connecting with Skype. 

We are using below configuration in Spectrum. 

[Skype.txt](https://github.com/hanzz/spectrum2/files/342828/Skype.txt)

**Comment by vitalyster** [comment]
You have `protocol` twice, delete `protocol=prpl-jabber`, there should be only `protocol=prpl-skypeweb`
And please show your logs if you still can't connect

**Comment by Ghabry** [comment]
do you use the latest git version of purple-skypeweb? The tagged version "1.1" doesn't work anymore since a few days.

**Comment by teamu** [comment]
@vitalyster 
we have updated the .cfg file but we still have issue.

Please find log below

`2756: 2016-07-01 06:00:03,184 INFO  libpurple: plugins:probing /usr/lib64/purple-2/one_time_password.so
2756: 2016-07-01 06:00:03,185 INFO  libpurple: plugins:probing /usr/lib64/purple-2/psychic.so
2756: 2016-07-01 06:00:03,185 INFO  libpurple: plugins:probing /usr/lib64/purple-2/ssl-nss.so
2756: 2016-07-01 06:00:03,186 INFO  libpurple: plugins:probing /usr/lib64/purple-2/ssl.so
2756: 2016-07-01 06:00:03,186 INFO  libpurple: plugins:probing /usr/lib64/purple-2/statenotify.so
2756: 2016-07-01 06:00:03,225 INFO  libpurple: util:Reading file xmpp-caps.xml from directory /var/lib/spectrum2/localhost
2756: 2016-07-01 06:00:03,225 INFO  libpurple: util:File /var/lib/spectrum2/localhost/xmpp-caps.xml does not exist (this is not necessarily an error)
2756: 2016-07-01 06:00:03,225 INFO  libpurple: jabber:creating hash tables for data objects
2756: 2016-07-01 06:00:03,225 INFO  libpurple: prefs:/purple/status/scores/offline changed, scheduling save.
2756: 2016-07-01 06:00:03,225 INFO  libpurple: prefs:/purple/status/scores/available changed, scheduling save.
2756: 2016-07-01 06:00:03,225 INFO  libpurple: prefs:/purple/status/scores/invisible changed, scheduling save.
2756: 2016-07-01 06:00:03,225 INFO  libpurple: prefs:/purple/status/scores/away changed, scheduling save.
2756: 2016-07-01 06:00:03,225 INFO  libpurple: prefs:/purple/status/scores/extended_away changed, scheduling save.
2756: 2016-07-01 06:00:03,225 INFO  libpurple: prefs:/purple/status/scores/idle changed, scheduling save.
2756: 2016-07-01 06:00:03,225 INFO  libpurple: prefs:/purple/status/scores/offline_msg changed, scheduling save.
2756: 2016-07-01 06:00:03,225 INFO  libpurple: util:Reading file accounts.xml from directory /var/lib/spectrum2/localhost
2756: 2016-07-01 06:00:03,225 INFO  libpurple: util:File /var/lib/spectrum2/localhost/accounts.xml does not exist (this is not necessarily an error)
2756: 2016-07-01 06:00:03,225 INFO  libpurple: util:Reading file status.xml from directory /var/lib/spectrum2/localhost
2756: 2016-07-01 06:00:03,225 INFO  libpurple: util:File /var/lib/spectrum2/localhost/status.xml does not exist (this is not necessarily an error)
2756: 2016-07-01 06:00:03,225 INFO  libpurple: certificate:CertificateVerifier x509, singleuse requested but not found.
2756: 2016-07-01 06:00:03,225 INFO  libpurple: certificate:CertificateVerifier singleuse registered
2756: 2016-07-01 06:00:03,225 INFO  libpurple: certificate:CertificatePool x509, ca requested but not found.
2756: 2016-07-01 06:00:03,225 INFO  libpurple: certificate:CertificateScheme x509 requested but not found.
2756: 2016-07-01 06:00:03,225 INFO  libpurple: certificate/x509/ca:Lazy init failed because an X.509 Scheme is not yet registered. Maybe it will be better later.
2756: 2016-07-01 06:00:03,225 INFO  libpurple: certificate/x509/ca:Init failed, probably because a dependency is not yet registered. It has been deferred to later.
2756: 2016-07-01 06:00:03,225 INFO  libpurple: certificate:CertificatePool ca registered
2756: 2016-07-01 06:00:03,225 INFO  libpurple: certificate:CertificatePool x509, tls_peers requested but not found.
2756: 2016-07-01 06:00:03,225 INFO  libpurple: certificate:CertificatePool tls_peers registered
2756: 2016-07-01 06:00:03,225 INFO  libpurple: certificate:CertificateVerifier x509, tls_cached requested but not found.
2756: 2016-07-01 06:00:03,225 INFO  libpurple: certificate:CertificateVerifier tls_cached registered
2756: 2016-07-01 06:00:03,225 INFO  libpurple: prefs:/purple/logging/format changed, scheduling save.
2756: 2016-07-01 06:00:03,225 INFO  libpurple: prefs:/purple/logging/format changed, scheduling save.
2756: 2016-07-01 06:00:03,228 INFO  libpurple: prefs:/purple/proxy/type changed, scheduling save.
2756: 2016-07-01 06:00:03,228 INFO  libpurple: prefs:/purple/proxy/host changed, scheduling save.
2756: 2016-07-01 06:00:03,228 INFO  libpurple: prefs:/purple/proxy/port changed, scheduling save.
2756: 2016-07-01 06:00:03,228 INFO  libpurple: prefs:/purple/proxy/username changed, scheduling save.
2756: 2016-07-01 06:00:03,228 INFO  libpurple: prefs:/purple/proxy/password changed, scheduling save.
2756: 2016-07-01 06:00:03,261 INFO  libpurple: certificate:CertificateScheme x509 requested but not found.
2756: 2016-07-01 06:00:03,261 INFO  libpurple: certificate:CertificateScheme x509 registered
2756: 2016-07-01 06:00:03,261 INFO  libpurple: util:Reading file smileys.xml from directory /var/lib/spectrum2/localhost
2756: 2016-07-01 06:00:03,261 INFO  libpurple: util:File /var/lib/spectrum2/localhost/smileys.xml does not exist (this is not necessarily an error)
2756: 2016-07-01 06:00:03,261 INFO  libpurple: stun:using server 
2756: 2016-07-01 06:00:03,261 INFO  libpurple: util:Reading file blist.xml from directory /var/lib/spectrum2/localhost
2756: 2016-07-01 06:00:03,261 INFO  libpurple: util:File /var/lib/spectrum2/localhost/blist.xml does not exist (this is not necessarily an error)
2756: 2016-07-01 06:00:03,261 INFO  libpurple: prefs:Reading /var/lib/spectrum2/localhost/prefs.xml
2756: 2016-07-01 06:00:03,261 INFO  libpurple: prefs:/pidgin/plugins/loaded changed, scheduling save.
2756: 2016-07-01 06:00:03,261 INFO  libpurple: prefs:Finished reading /var/lib/spectrum2/localhost/prefs.xml
2756: 2016-07-01 06:00:08,081 INFO  libpurple: util:Writing file prefs.xml to directory /var/lib/spectrum2/localhost
2756: 2016-07-01 06:00:08,081 INFO  libpurple: util:Writing file /var/lib/spectrum2/localhost/prefs.xml
2756: 2016-07-01 06:00:22,907 INFO  backend: Exiting...`

**Comment by vitalyster** [comment]
It looks like you still loading prpl-jabber
And there is also another `spectrum.log`

**Comment by noob2020** [comment]
please check https://community.igniterealtime.org/docs/DOC-2601

try to edit your jid = skype.xxxxxx (xxxxx  is your domainname)
add:  admin_jid = gojaraadmin@yourdomainname

**Comment by teamu** [comment]
@noob2020 thanks for your help.
I have followed your instructions and Configuration seems to be all fine now.

Now how can I login to Skype Account? Do I need to use Skype Credentials directly on Spark or need to create a group and add user there.
I followed this article https://community.igniterealtime.org/docs/DOC-2601, but still need little help.  
I am adding 4 snapshots of Openfire dashboard.
![gateway_session](https://cloud.githubusercontent.com/assets/2108184/16538871/9390d7d8-404e-11e6-9a85-ec00b17148c2.png)
![component_session](https://cloud.githubusercontent.com/assets/2108184/16538872/93ca20f6-404e-11e6-87d4-c74c2d182bd8.png)
![spectrum_stats](https://cloud.githubusercontent.com/assets/2108184/16538873/93e3261e-404e-11e6-8c49-e4e772c8b152.png)
![connected_gateways](https://cloud.githubusercontent.com/assets/2108184/16538874/93f0060e-404e-11e6-82b4-54464ed4d4a8.png)




We are very close just need few info. Appreciate your help.

**Comment by noob2020** [comment]
i'm so sorry i can't help you cuz i can't remember my old configuration for gojara. 
i used ubuntu+ejabberd+pidgin now and that is simple not like openfire.

**Comment by vitalyster** [comment]
closed as inactive
