### ISSUE TITLE
Skype group contact doesn't work.

### ISSUE THREAD

**Issue by Strasser-Pablo** [hanzz/spectrum2#157]
I tried the skype-web plugin it work very well for user however it fail to comunicate with group.
However it work with pidgin with the skype web plugin.

I'm using the docker instalation.

**Comment by vitalyster** [comment]
What XMPP client you are using? Groups should be listed in "service discovery" window

**Comment by Strasser-Pablo** [comment]
Hi, I'm using Gajim. In fact I'm able to see the group chat with horrible name, however if I connect to them and see a chat windows but cannot type text. I installed on the same computer spectrum2 by hand and its working perfectly and can see the "user friendly" skype name of the group. It seem the docker image is out of date for skype group.

Thanks for your reply.

**Comment by vitalyster** [comment]
Yes, it was fixed after 2.0.3 release, but not yet released
