### ISSUE TITLE
error compile

### ISSUE THREAD

**Issue by noob2020** [hanzz/spectrum2#165]
sorry if my english is not good..

last month I tried compile with trusty and  no found error
but now i tried compile with wily found error : 

../../libtransport/libtransport.so.2.0: undefined reference to `pqxx::connection_base::esc(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../../libtransport/libtransport.so.2.0: undefined reference to `pqxx::transaction_base::exec(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../../libtransport/libtransport.so.2.0: undefined reference to `pqxx::internal::throw_null_conversion(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../../libtransport/libtransport.so.2.0: undefined reference to `pqxx::string_traits<long>::to_string[abi:cxx11](long)'
../../libtransport/libtransport.so.2.0: undefined reference to `pqxx::string_traits<int>::to_string[abi:cxx11](int)'
../../libtransport/libtransport.so.2.0: undefined reference to `pqxx::connectionpolicy::connectionpolicy(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
backends/libpurple/CMakeFiles/spectrum2_libpurple_backend.dir/build.make:185: recipe for target 'backends/libpurple/spectrum2_libpurple_backend' failed
make[2]: *** [backends/libpurple/spectrum2_libpurple_backend] Error 1
CMakeFiles/Makefile2:530: recipe for target 'backends/libpurple/CMakeFiles/spectrum2_libpurple_backend.dir/all' failed
make[1]: *** [backends/libpurple/CMakeFiles/spectrum2_libpurple_backend.dir/all] Error 2
Makefile:136: recipe for target 'all' failed
make: *** [all] Error 2

I missing packages files or what?

**Comment by vitalyster** [comment]
`make clean` first?

**Comment by noob2020** [comment]
No,  but why make clean first? Cause that is fresh wily instalation.

**Comment by vitalyster** [comment]
You have some packages compiled with older c++ abi (libpqxx?), and should rebuild them with your distribution. If this broken packages was not compiled by you - then it is bug in you distribution
