### ISSUE TITLE
Debian init script/systemd unit file not in built .deb package

### ISSUE THREAD

**Issue by Niluge-KiWi** [hanzz/spectrum2#167]
Since #55 there are debian init script/systemd unit file in the source repository, but they are not used in the .deb package build, so they are not installed and usable when installing spectrum2 with .deb files.

**Comment by vitalyster** [comment]
You should build master, aren't you?

**Comment by Niluge-KiWi** [comment]
I saw 2015, and assumed it was closed before the last .deb of February 2016
that is available on your apt repository.

I assumed wrong.

You can close the issue, sorry.
