### ISSUE TITLE
Problem with Facebook transport

### ISSUE THREAD

**Issue by beherit** [hanzz/spectrum2#170]
I have problem with Facebook transport - always I have an error message "Application does not have permission for this action (10)". How to fix it?

**Comment by vitalyster** [comment]
Which backend you are using for Facebook? purple-xmpp or purple-facebook?

**Comment by beherit** [comment]
purple-facebook

**Comment by vitalyster** [comment]
So I think it is plugin issue, maybe @dequis can help?

**Comment by dequis** [comment]
Weird. Never heard of this one. Please open a ticket in the other tracker https://github.com/dequis/purple-facebook/issues

Also: did it ever work before? Have you messed with security settings at the facebook website in any way?

@vitalyster While I'm here, how should i request debug logs from spectrum users? The plugin requires enabling 'verbose' and 'unsafe' debug to get useful stuff out of it. That usually means the PURPLE_UNSAFE_DEBUG=1 PURPLE_VERBOSE_DEBUG=1 environment variables. What's a good way to get spectrum to pass those to the backend?

**Comment by noob2020** [comment]
facebook  work for me .. i used apt from https://jgeboski.github.io/#package-repositories

**Comment by beherit** [comment]
I have this issue after switching VPS, on previous machine I had older version of purple-facebook, on new VPS I have latest version from https://jgeboski.github.io/#package-repositories and now transport doesn't work :( @noob2020  Could You share Your config file? Where put PURPLE_UNSAFE_DEBUG=1 PURPLE_VERBOSE_DEBUG=1 ?

**Comment by noob2020** [comment]
please read https://github.com/dequis/purple-facebook/wiki/Debugging-Logs

**Comment by dequis** [comment]
Those instructions are meant for pidgin, which is why i asked @vitalyster for an equivalent that applies to spectrum...

**Comment by beherit** [comment]
It's strange because today transport started work again but only for a while... I registered into transport on my server via Gajim, I got all contacts on my rooster, after allowing subscriptions to all contacts I have message from transport "Application does not have permission for this action (10)". Maybe it's a ban or something?

**Comment by vitalyster** [comment]
@dequis there is no configuration options currently, someone who can compile spectrum from sources can add required lines here - https://github.com/hanzz/spectrum2/blob/master/backends/libpurple/main.cpp#L2125
I will think about adding configuration options

**Comment by beherit** [comment]
In backend logs I see this:
```
2016-10-27 09:52:34,057 INFO  libpurple: certificate:Successfully verified certificate for b-api.facebook.com
2016-10-27 09:52:34,241 INFO  libpurple: http:Got main header with code 200
2016-10-27 09:52:34,241 INFO  libpurple: http:Got headers end
2016-10-27 09:52:34,241 INFO  libpurple: http:releasing a socket: 0x117d030
2016-10-27 09:52:34,241 INFO  libpurple: http:Request 0x1158fc0 performed successfully.
2016-10-27 09:52:34,241 INFO  libpurple: connection:Connection error on 0x1193560 (reason: 0 description: Application does not have permission for this action (10))
```

**Comment by noob2020** [comment]
mys spectrum configuration

[service]
jid = fb.myhost
password = secret
server = 127.0.0.1
port = 5560
backend_host = 127.0.0.1
users_per_backend=10
backend=/usr/local/bin/spectrum2_libpurple_backend
protocol=prpl-facebook

[identity]
name=Facebook Center
type=xmpp

[logging]
config = /etc/spectrum2/logging.cfg
backend_config = /etc/spectrum2/backend-logging.cfg

[database]
type = sqlite3

[registration]
enable_public_registration=1

[purple]
show-unread=false

**Comment by beherit** [comment]
https://github.com/dequis/purple-facebook/issues/281
