### ISSUE TITLE
Can't install spectrum2 packages on Ubuntu 14.04 - depends on libprotobuf9 that not available

### ISSUE THREAD

**Issue by MurzNN** [hanzz/spectrum2#172]
When I try to install package via this manual http://spectrum.im/documentation/installation/packages_debian_ubuntu.html on Ubuntu 14.04 LTS - I got the error:
```
The following packages have unmet dependencies:
 spectrum2 : Depends: libtransport2.0 (= 1:2.0.3-1) but it is not going to be installed
             Depends: libtransport-plugin2.0 (= 1:2.0.3-1) but it is not going to be installed
             Depends: libprotobuf9 but it is not installable
 spectrum2-backend-libpurple : Depends: libtransport2.0 (= 1:2.0.3-1) but it is not going to be installed
                               Depends: libtransport-plugin2.0 (= 1:2.0.3-1) but it is not going to be installed
                               Depends: libprotobuf9 but it is not installable
E: Unable to correct problems, you have held broken packages.
```
On ubuntu 14.04 there are only libprotobuf8 version of package available. Version libprotobuf9 is available only on fresh ubuntu 16.04 version: http://packages.ubuntu.com/search?keywords=libprotobuf9

Can spectrum2 works with 8 version of libprotobuf library? Or maybe we can provide updated version of libprotobuf for Ubuntu 14.04 or PPA?

**Comment by MurzNN** [comment]
Same problem with dependencies - on Ubuntu 16.04:
```
# LANG=C apt install spectrum2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 spectrum2 : Depends: libtransport2.0 (= 1:2.0.3-1) but it is not going to be installed
             Depends: libtransport-plugin2.0 (= 1:2.0.3-1) but it is not going to be installed
             Depends: libboost-date-time1.55.0 but it is not installable
             Depends: libboost-filesystem1.55.0 but it is not installable
             Depends: libboost-locale1.55.0 but it is not installable
             Depends: libboost-program-options1.55.0 but it is not installable
             Depends: libboost-regex1.55.0 but it is not installable
             Depends: libboost-signals1.55.0 but it is not installable
             Depends: libboost-system1.55.0 but it is not installable
             Depends: libboost-thread1.55.0 but it is not installable
             Depends: liblog4cxx10 but it is not installable
             Depends: libmysqlclient18 (>= 5.5.24+dfsg-1) but it is not installable
             Depends: libprotobuf9 but it is not installable
             Depends: libswiften2 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by vitalyster** [comment]
You should read the second section of the manual and built packages yourself, it will pick correct dependencies for your distribution automatically. Sorry, we have no time and resources to provide binary packages for all debian-based distros.
And also you can use docker image if you are familiar with docker.

**Comment by palmtown** [comment]
+1 I'm getting an error using the manual method.  I followed instructions on http://spectrum.im/documentation/installation/packages_debian_ubuntu.html

dget: using existing communi_3.4.0.orig.tar.gz
dget: using existing communi_3.4.0-1.debian.tar.xz
communi_3.4.0-1.dsc:
dscverify: communi_3.4.0-1.dsc failed signature check:
gpg: Signature made Wed 08 Jun 2016 08:37:40 AM UTC using RSA key ID 1AFDEA51
gpg: Can't check signature: public key not found
Validation FAILED!!

**Comment by vitalyster** [comment]
@palmtown you didn't install key in the correct keychain

**Comment by palmtown** [comment]
Thanks for your reply, how would I do that?  I ran the commands exactly as shown.

**Comment by vitalyster** [comment]
https://askubuntu.com/questions/195489/added-key-but-dget-still-shows-gpg-cant-check-signature-public-key-not-foun

**Comment by palmtown** [comment]
I tried that, here is the error I get:

dget: retrieving http://packages.spectrum.im/spectrum2/pool/main/c/communi/communi_3.4.0-1.dsc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1540  100  1540    0     0   5144      0 --:--:-- --:--:-- --:--:--  5150
dget: using existing communi_3.4.0.orig.tar.gz
dget: using existing communi_3.4.0-1.debian.tar.xz
communi_3.4.0-1.dsc:
dscverify: communi_3.4.0-1.dsc failed signature check:
gpg: keyblock resource `/root/.gnupg/pubring.gpg': file open error
gpg: Signature made Wed 08 Jun 2016 08:37:40 AM UTC using RSA key ID 1AFDEA51
gpg: Good signature from "Vitaly Takmazov <vitalyster@gmail.com>"
gpg: WARNING: Using untrusted key!
Validation FAILED!!

**Comment by vitalyster** [comment]
Do not run this from root user, or install key in root keyring too

**Comment by palmtown** [comment]
how to install keyring in root?

**Comment by vitalyster** [comment]
Run first apt-key command from root

**Comment by palmtown** [comment]
I already did that too, here is the results:

apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-keys 1AFDEA51
Executing: /tmp/tmp.I9lVFLyLgq/gpg.1.sh --keyserver
hkp://pool.sks-keyservers.net
--recv-keys
1AFDEA51
gpg: requesting key 1AFDEA51 from hkp server pool.sks-keyservers.net
gpg: key 1AFDEA51: "Vitaly Takmazov <vitalyster@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1

**Comment by palmtown** [comment]
This is the only file in the ~/root/.gnupg dir:

total 0
-rw------- 1 root root 0 May 14 06:17 secring.gpg

**Comment by vitalyster** [comment]
And now you should point dscverify to correct keychain

**Comment by palmtown** [comment]
How do I do that?

**Comment by vitalyster** [comment]
Read the link from askubuntu again and check the path in the command

**Comment by palmtown** [comment]
I just tried that:

DSCVERIFY_KEYRINGS="/etc/apt/trusted.gpg:~/.gnupg/pubring.gpg:~/.gnupg/secring.gpg"

**Comment by vitalyster** [comment]
Which of these key rings have my key?

**Comment by vitalyster** [comment]
And which user ~ directory used?

**Comment by palmtown** [comment]
I am using root, and I am not sure how to tell which one has your directory.  I copied it from the example, and I added ~/.gnupg/secring.gpg for testing, but that didn't work.

**Comment by vitalyster** [comment]
Your last output say it can not open keyring, so you have wrong path in DSCVERIFY_KEYRINGS

**Comment by palmtown** [comment]
What is the correct path?  Also, /root/.gnupg/secring.gpg is empty.

**Comment by vitalyster** [comment]
Correct path is the path to keyring with my key, I don't know in which keyring you have placed the key :)

**Comment by palmtown** [comment]
Thanks for your reply, but not I did not manual put any key.  I just followed the documentation step for step.  Therefore, can you tell me the steps I need to take to put the key in the right place?  I ran the command apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-keys 1AFDEA51

**Comment by vitalyster** [comment]
And this command write the key to some keyring. And exactly that keyring should be used by dscverify

**Comment by palmtown** [comment]
Ok, I was to move pass this error after very much trial, error and good old fashion system engineering, almost to the end, however, got one dependency issue.  Before I get to that, let me explain the key issue.

In short, first, your manual instructions for me did not work on Ubuntu 16 due to the key issue.  What I found is that when I run the command dget -x http://packages.spectrum.im/spectrum2/pool/main/c/communi/communi_3.4.0-1.dsc, it is looking for the *** public key *** at /root/.gnupg/pubring.gpg but that is not there.   Your key is installed at /etc/apt/trusted.gpg which I verified as shown below using apt-key list.

Therefore, I created an empty file /root/.gnupg/pubring.gpg and it allowed me to unpack and move forward.  I got to the last command **cd spectrum2_2.0.3-1 && DEB_BUILD_OPTIONS=nocheck dpkg-buildpackage -rfakeroot -us -uc  && cd ..** and had 2 issues as follows:

1. The directory name is not cd spectrum2_2.0.3-1, it is spectrum2-2.0.3 so that should be changed in your manual.
2. **libswiften-dev is not found.**  Therefore, the last command files.

Given the above, I am stuck at installing libswiften-dev, up to now, I haven't found a workaround.

**Command:**  apt-key list
/etc/apt/trusted.gpg
--------------------
pub   1024D/437D05B5 2004-09-12
uid                  Ubuntu Archive Automatic Signing Key <ftpmaster@ubuntu.com>
sub   2048g/79164387 2004-09-12

pub   4096R/C0B21F32 2012-05-11
uid                  Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>

pub   4096R/EFE21092 2012-05-11
uid                  Ubuntu CD Image Automatic Signing Key (2012) <cdimage@ubuntu.com>

pub   1024D/FBB75451 2004-12-30
uid                  Ubuntu CD Image Automatic Signing Key <cdimage@ubuntu.com>

pub   2048R/1AFDEA51 2015-01-07
uid                  Vitaly Takmazov <vitalyster@gmail.com>
sub   2048R/5FE78F29 2015-01-07

**Comment by palmtown** [comment]
After searching around, I come to find libswiften-dev is not available on Ubuntu 16, it is on Ubuntu 14.  Does this mean the project is dead starting at Ubuntu 16?

**Comment by vitalyster** [comment]
libswiften is available from swift.im repository: put `deb http://swift.im/packages/ubuntu/xenial development main` in your sources.list

**Comment by palmtown** [comment]
Hello,

That worked in part, however, still failed at the end.  Here are my notes:

1.  Even when you add  deb http://swift.im/packages/ubuntu/xenial development main, it needs the below dependencies, therefore, I added those:

**apt-get install libswiften-dev libswiften4 libminiupnpc10 libnatpmp1** 

2. Once you add dependencies and move forward, the build fails with error:

[  1%] Building CXX object plugin/cpp/CMakeFiles/transport-plugin.dir/__/__/libtransport/Logging.cpp.o
cd /root/spectrum/spectrum2-2.0.3/plugin/cpp && /usr/bin/x86_64-linux-gnu-g++   -DBOOST_FILESYSTEM_VERSION=3 -DBOOST_SIGNALS_NO_DEPRECATION_WARNING -DDEBUG -DIRC_SHARED -DPURPLE_RUNTIME=0 -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DSPECTRUM_VERSION=\"2.0.3\" -DSUPPORT_LEGACY_CAPS -DWITH_LOG4CXX -DWITH_MYSQL -DWITH_PQXX -DWITH_PROTOBUF -DWITH_SQLITE -Dtransport_plugin_EXPORTS -isystem /usr/include/qt4 -isystem /usr/include/qt4/QtGui -isystem /usr/include/qt4/QtCore -I/usr/include/mysql -I/usr/include/libpurple -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/qt4/QtNetwork -I/usr/include/qt4/Communi/IrcCore -I/usr/include/qt4/Communi/IrcUtil -I/usr/include/qt4/Communi/IrcModel -I/root/spectrum/spectrum2-2.0.3/include  -g -fPIC   -O0 -ggdb -fPIC -o CMakeFiles/transport-plugin.dir/__/__/libtransport/Logging.cpp.o -c /root/spectrum/spectrum2-2.0.3/libtransport/Logging.cpp
In file included from /usr/include/Swiften/StringCodecs/Base64.h:12:0,
                 from /root/spectrum/spectrum2-2.0.3/include/transport/Util.h:27,

Therefore, I deployed it via Debian and that worked without any errors and now I can get right into testing the product.  On Ubuntu 16+, there needs to be some work investigated to correct the issues.

**Comment by palmtown** [comment]
Are you available for hire?  I need to help with connecting with the available IM providers and looking for someone who can set it up now that I have a working installation which can save me some time.
