### ISSUE TITLE
Odd corner case with libpurple XMPP transport

### ISSUE THREAD

**Issue by kettlekat** [hanzz/spectrum2#174]
The libpurple XMPP transport appears to prevent registration of the same JID that is connected to the transport so as to prevent infinite recursion.  HOWEVER, there are situations in which this is perfectly safe.  If you configure a connect_server for the transport in [purple] options different from the hosting server, registration should be allowed.

Example:  I have Google Apps set up on domain thryse.com, including GTalk/Hangouts, but I prefer to use my own XMPP server. I configured prosody + spectrum for thryse.com and set my DNS SRV records accordingly. I want to connect to my server with JID kaitlyn@thryse.com, which happens to be identical to my GApps account.  By setting connect_server=talk.google.com in an XMPP transport, I've created a specialized GTalk transport which can register any valid Google account EXCEPT if the JID to register is identical to the connected JID.  Spectrum should check connect_server against the SRV record for the domain the client is connected with, and if it differs, permit the registration.  A simpler workaround would be disabling the JID recursion check if connect_server is specified.

**Comment by kettlekat** [comment]
My goal is to register my GApps account on a libpurple XMPP transport where my GApps JID and my JID on my server are identical.

**Comment by vitalyster** [comment]
>  I have Google Apps set up on domain thryse.com
In this case you MUST have DNS SRV records pointing to Google chat service, managing multiple chat services on the same domain is out of spectrum scope. "connect_server" is just a dirty hack for poor implemented servers/clients and should NOT be used with properly configured DNS
