### ISSUE TITLE
Set purple-facebook specific parameters

### ISSUE THREAD

**Issue by mw80** [hanzz/spectrum2#176]
Hi,

purple-facebook provides following parameters. Is it possible to set them for a transport?
show-unread
group-chat-open
show-self

Best regards
M

**Comment by vitalyster** [comment]
http://spectrum.im/documentation/backends/libpurple.html
See "setting-libpurple-plugins-configurations" part

**Comment by mw80** [comment]
Yes, I tried it but the backend immediately crashed.

[purple]
show-self=1

**Comment by vitalyster** [comment]
So please open different issue with "backend crashed with xxx setting" and a backtrace
