### ISSUE TITLE
libpurple backend crashing when setting boolean purple parameter to 1

### ISSUE THREAD

**Issue by mw80** [hanzz/spectrum2#177]
Hi,

I am trying to set a boolean purple parameter to 1.

Test case 1: OK
[purple]
group-chat-open=0
-> accounts.xml:<setting name='group-chat-open' type='bool'>0</setting>

Test case 2: NOT OK
[purple]
group-chat-open=1
-> purple backend crashing before accounts.xml written

backend-1.log: 
2017-01-03 19:43:24,711 INFO  backend: Exiting...

**Comment by vitalyster** [comment]
Which version you have tested? 2.0.2, 2.0.3 and git head may act differ

**Comment by mw80** [comment]
debian-apt version 2.0.3-1. 
I am using prpl-facebook.

**Comment by mw80** [comment]
It is even crashing with following config. test=0 works fine.

[purple]
test=1

**Comment by mw80** [comment]
Seems to be related to the following commit: 
https://github.com/hanzz/spectrum2/commit/68527d73e2b85c6488c8be36e668ed530c4fbb9e

line 222 and 225 have equal conditions. Don't think this is correct.

libtransport/Config.cpp 
 222   +				if (opt.value[0] == "true" || opt.value[0] == "1") {  
 223   +					m_unregistered[opt.string_key] = variable_value(true, false);  
 224   +				}  
 225   +				else if (opt.value[0] == "true" || opt.value[0] == "1") {  
 226   +					m_unregistered[opt.string_key] = variable_value(false, false);

**Comment by vitalyster** [comment]
Fixed
