### ISSUE TITLE
When Facebook is used with Spectrum 2, some users are just a UIN.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [hanzz/spectrum2#181]
I've recently started using Spectrum 2, to use the Pidgin Plugin with Xabber on Android. However it seems as though the user names often result in extremely_long_uin@facebook.domain rather than the rendered names. Sometimes you can see Profile pictures but it seems totally random when this happens.

**Comment by Zombie-Ryushu** [comment]
The version of Spectrum is 2.0.3
ejabberd 2.1.13 (with patches)
purple-facebook-0.9.0

**Comment by Zombie-Ryushu** [comment]
This issue also affects funyahoo-plusplus from EionRobb, but not aim, or purple-skypeweb

**Comment by drdownload** [comment]
Hi, do you have the same problem when using purple-facebook directly with pidgin?

**Comment by Zombie-Ryushu** [comment]
No, but under Pidgin, the "Get Info" page is blank for some users. It is believed that this is where Spectrum derives its info.

**Comment by vitalyster** [comment]
what is your client? I believe it is an issue solved 6 years ago by using either XEP-0144: Roster Exchange capable client, or XEP-0320: Remote Roster capable server

**Comment by Zombie-Ryushu** [comment]
Pidgin on Linux and Xabber on Android,

**Comment by vitalyster** [comment]
Please read how to configure Remote Roster support on ejabberd
