### ISSUE TITLE
Google Talk/Hangouts roster not manageable

### ISSUE THREAD

**Issue by mbirth** [hanzz/spectrum2#187]
Whenever I connect to my ejabberd with Gajim, I get an "Add me to your roster" request from a Google Talk/Hangouts contact. Even if I click on "Deny", the request appears on the next connection to my server.

Also deleting people from my roster doesn't seem to be synchronised back to Google Talk as they reappear on the next connection.

Is it possible to add such feature? Or am I doing something wrong?

**Comment by vitalyster** [comment]
add transport jid to `managers`, see https://docs.ejabberd.im/admin/configuration/#modroster

**Comment by thundergreen** [comment]
Roster manager in Ejabberd works perfectly.if u need bits of configuration file..Just let me know

**Comment by mbirth** [comment]
After adding the transport jid to the mod_roster config, I still got the request on each connection. However, I've now accepted it and immediately deleted the added contact again. This seems to have fixed it. (Didn't work before.) Thank you!

**Comment by vitalyster** [comment]
you may need to re-register on transport to eliminate subscription requests
