### ISSUE TITLE
Telegram Groups/Channels not visible

### ISSUE THREAD

**Issue by mightyBroccoli** [hanzz/spectrum2#190]
I am using spectrum2 with a compiled dev-1.4.0 version of telegram-purple. It works fine I can send and receive messages and everything works. But my Channels and even normal groups are completely absend. But in the backend log I can see that the server receive the messages but my client is not displaying anything.  In the backend log I get the message.

> 4949: 2017-03-30 17:29:26,212 INFO  backend: Received message body='Message' xhtml='' name='Channel NAme' Random Person
> 4949: 2017-03-30 17:29:26,213 ERROR backend: GLib g_string_free: assertion 'string != NULL' failed

 I am not sure what I did wrong.

---- edit ----
Ok I just recompiled the 1.3.0 version and now I can see the channel messages in the logfile but not in my im client. This is the reaction in the backend log file.

> 11248: 2017-03-30 18:05:02,811 INFO  libpurple: prpl-telegram:tgp_msg_recv before=(nil) server_id=5381
> 11248: 2017-03-30 18:05:02,811 INFO  libpurple: prpl-telegram:setting channel message server_id=
> 11248: 2017-03-30 18:05:02,811 INFO  backend: Received message body='message' xhtml='' name='creative Channel Name' mightyBroccoli
> 11248: 2017-03-30 18:05:02,811 INFO  libpurple: prpl-telegram:sending all pending recipes
> 11248: 2017-03-30 18:05:02,811 INFO  libpurple: prpl-telegram:tgl_do_mark_read (1078253661)
> 11248: 2017-03-30 18:05:02,812 INFO  libpurple: prpl-telegram:Sent query #6403323324534081536 of size 24 to DC 2
> 11248: 2017-03-30 18:05:02,812 INFO  libpurple: prpl-telegram:tgp_msg_process_in_ready, queue size=0
> 11248: 2017-03-30 18:05:02,812 INFO  libpurple: prpl-telegram:wrote state file: wpts=16230 wqts=0 wseq=150 wdate=1490889890
> 11248: 2017-03-30 18:05:02,812 INFO  libpurple: prpl-telegram:wrote secret chat file: 0 chats written.

I am using the latest Gajim and the latest Pidgin.

**Comment by vitalyster** [comment]
Use Service Discovery on the transport JID, there should be your groupchats. But there was issue in telegram plugin itself - https://github.com/majn/telegram-purple/issues/295
Please check

**Comment by mightyBroccoli** [comment]
I am not sure if I cause that but I can not do that. Gajim reports not searchable There are no objects which could be searched and Pidgin just replies an empty field.
But in the backend log I get:
> 11248: 2017-03-30 18:19:02,535 ERROR backend: g_log tgp_blist_lookup_peer_get: assertion 'id' failed
> 11248: 2017-03-30 18:19:02,535 ERROR backend: g_log tgp_blist_lookup_peer_get: assertion 'id' failed
> 11248: 2017-03-30 18:19:02,550 ERROR backend: g_log tgp_blist_lookup_peer_get: assertion 'id' failed
> 11248: 2017-03-30 18:19:02,550 ERROR backend: g_log tgp_blist_lookup_peer_get: assertion 'id' failed
> 11248: 2017-03-30 18:19:02,550 ERROR backend: g_log tgp_blist_lookup_peer_get: assertion 'id' failed
> 11248: 2017-03-30 18:19:02,550 ERROR backend: g_log tgp_blist_lookup_peer_get: assertion 'id' failed
> 11248: 2017-03-30 18:19:02,586 ERROR backend: g_log tgp_blist_lookup_peer_get: assertion 'id' failed
> 11248: 2017-03-30 18:19:02,673 ERROR backend: g_log tgp_blist_lookup_peer_get: assertion 'id' failed
> 11248: 2017-03-30 18:19:02,775 ERROR backend: g_log tgp_blist_lookup_peer_get: assertion 'id' failed
> 11248: 2017-03-30 18:19:02,873 ERROR backend: g_log tgp_blist_lookup_peer_get: assertion 'id' failed
> 11248: 2017-03-30 18:19:02,975 ERROR backend: g_log tgp_blist_lookup_peer_get: assertion 'id' failed
> 11248: 2017-03-30 18:19:03,075 ERROR backend: g_log tgp_blist_lookup_peer_get: assertion 'id' failed

I get this error like 50 times everytime i click search.

**Comment by vitalyster** [comment]
Yeah, it was the same for me. Add +1 to mentioned telegram-purple issue :)

**Comment by vitalyster** [comment]
Ah, did you see groups in Pidgin client directly without spectrum? If no, it is a different issue

**Comment by mightyBroccoli** [comment]
That is the weird thing. Yes I can use the plugin without any issues on my local pidgin. I can see the groups and everything. Thats why I am that confused :D

**Comment by mightyBroccoli** [comment]
I just tested the 1.4.0 dev and even there this is not working. I hope somebody is fixing this in the near future. I would love to just use gajim and not gajim for everything and pidgin for telegram group chat :D

**Comment by mightyBroccoli** [comment]
I am using the plugin inside pidgin locally and with the same account inside my spectrum2 transport. The only difference I found is within the account.xml of purple.
In my local installation of purple the accounts.xml 
```
<account>
		<protocol>prpl-telegram</protocol>
		<name>+phonenumber</name>
		<statuses/>
		<settings>
			<setting name='media-size-threshold' type='int'>8192</setting>
			<setting name='buddy_icon_timestamp' type='int'>0</setting>
			<setting name='send-read-notifications' type='bool'>1</setting>
			<setting name='password-two-factor' type='string'></setting>
			<setting name='last-server-id/123456789' type='int'>6047</setting>
			<setting name='inactive-days-offline' type='int'>5</setting>
			<setting name='compat-verification' type='bool'>0</setting>
			<setting name='display-read-notifications' type='bool'>1</setting>
			<setting name='accept-secret-chats' type='string'>ask</setting>
			<setting name='history-retrieve-days' type='int'>30</setting>
			<setting name='auto-join-group-chats' type='bool'>1</setting>
			<setting name='use-global-buddyicon' type='bool'>1</setting>
		</settings>
		<current_error/>
</account>
```
and on the server spectrum instance of purple the account.xml
```
<account>
		<protocol>prpl-telegram</protocol>
		<name>+phonenumber</name>
		<alias>mightyBroccoli</alias>
		<statuses/>
		<settings>
			<setting name='custom_smileys' type='bool'>0</setting>
			<setting name='direct_connect' type='bool'>0</setting>
			<setting name='buddy_icon' type='string'><ydgsdxhcfzj.png</setting>
			<setting name='compat-verification' type='bool'>1</setting>
			<setting name='last-server-id/1078253661' type='int'>6047</setting>
			<setting name='buddy_icon_timestamp' type='int'>1491861237</setting>
		</settings>
		<settings ui='spectrum'>
			<setting name='auto-login' type='bool'>1</setting>
		</settings>
		<current_error/>
</account>
```
I am not sure if this is helpfull. But could it be that the plugin responds correctly and spectrum just misses to add the settings?

**Comment by vitalyster** [comment]
Looks like it works now with telegram-purple from dev-1.4.0 branch

**Comment by mightyBroccoli** [comment]
not really though I dont get messeges at all. I can see the rooms now but they are all empty and dont recieve anything.

**Comment by vitalyster** [comment]
@mightyBroccoli I'm watching now it, and sometimes it throws multiple messages from history, sometimes it does not receive anything

**Comment by vitalyster** [comment]
@mightyBroccoli also, please try to write something, sometimes it triggers message receiving for me :)

**Comment by mightyBroccoli** [comment]
I did try to send messages. The dont apear in the chat window or get send.

**Comment by thundergreen** [comment]
@mighty did u add managers to mod_roster?

**Comment by mightyBroccoli** [comment]
@thundergreen mod_roster is server side, and yes I do have mod roster that is kind of a must have, but i think you mean  XEP-0321: Remote Roster Management  and do also have that installed.
