### ISSUE TITLE
Error when running docker image on same host as XMPP server

### ISSUE THREAD

**Issue by k0sebamse** [hanzz/spectrum2#194]
Hi,

I just wanted to install Spectrum2 using docker. But when I want to start the container I get the following error message:
`docker: Error response from daemon: driver failed programming external connectivity on endpoint spectrum2 (d7d8014a6a9c0cbcb04eeb08e32240dc4083dbaf7b75d3318b426e761e5d05cd): Error starting userland proxy: listen tcp 127.0.0.1:5222: bind: address already in use.`

I run prosody on the same machine whic is using port 5222. How can I run Prosody and Spectrum Docker image on the same machine?

Thank you in advance.

Regards
Mirco

**Comment by vitalyster** [comment]
You can bind container port to any other host port, like -p 443:5222 where 443 is the host port. For details see [Docker documentation](https://docs.docker.com/engine/userguide/networking/default_network/binding/)
