### ISSUE TITLE
Gentoo overlay

### ISSUE THREAD

**Issue by sdfg2** [hanzz/spectrum2#195]
The overlay doesn't contain net-im/communi, which is a dependency of spectrum.

Also, it seems that the overlay is filled with things that are already in the main tree, like ejabberd, and what -is- there is very outdated. 

Finally, following the documentation, there is an error "Section 'spectrum2' in repos.conf has name different from repository name 'chain' set inside repository".

**Comment by vitalyster** [comment]
Where did you find the link to that overlay?

**Comment by sdfg2** [comment]
http://spectrum.im/documentation/installation/gentoo.html

**Comment by vitalyster** [comment]
I've removed this page as it is outdated. Consider to use Docker image
