### ISSUE TITLE
Invalid protocol prpl-facebook

### ISSUE THREAD

**Issue by QomariSanjaya** [hanzz/spectrum2#196]
Why i got this error message when trying to connect to facebook?
Invalid protocol prpl-facebook
Ive already config the path to the library correctly

Here is my config

```
[service]
# The name of user/group Spectrum runs as.
#user=spectrum
#group=spectrum

# JID of Spectrum instance.
jid = facebook.fb.example.com
admin_jid = gojaraadmin@fb.example.com

# Password used to connect the XMPP server.
password = secret

# XMPP server to which Spectrum connects in gateway mode.
server = 127.0.0.1

# XMPP server port.
port = 5347

# Interface on which Spectrum listens for backends.
backend_host = 127.0.0.1

# Port on which Spectrum listens for backends.
# By default Spectrum chooses random backend port and there's
# no need to change it normally
#backend_port=10001

# Number of users per one legacy network backend.
users_per_backend=10
# For Skype - must be =1
#users_per_backend=1

# Full path to backend binary.
backend=/usr/bin/spectrum2_libpurple_backend
#backend=/usr/bin/spectrum2_libcommuni_backend
# For skype:
#backend=/usr/bin/xvfb-run -a -s "-screen 0 10x10x8" -f /tmp/x-skype-gw /usr/bin/spectrum2_skype_backend
# For skype if instance drops privileges (`user`/`group` options) we should set writable HOME folder for D-BUS:
#backend=/usr/bin/env HOME=/var/lib/spectrum2 xvfb-run -a -s "-screen 0 10x10x8" -f /tmp/x-skype-gw /usr/bin/spectrum2_skype_backend

# Libpurple protocol-id for spectrum_libpurple_backend
protocol=prpl-facebook
#protocol=prpl-msn
#protocol=prpl-icq

# protocol=any means that user sets his protocol in his JID which has to be
# in following format: protocol.username@domain.tld
# So for example: prpl-jabber.hanzz.k%gmail.com@domain.tld
#protocol=any

[identity]
# Name of Spectrum instance in service discovery
name=Facebook Transport

# Type of transport ("msn", "icq", "xmpp").
# Check http://xmpp.org/registrar/disco-categories.html#gateway
type=facebook

# Category of transport, default is "gateway
category=gateway

[logging]
# log4cxx/log4j logging configuration file in ini format used for main spectrum2 instance.
config = /etc/spectrum2/logging.cfg

# log4cxx/log4j logging configuration file in ini format used for backends.
backend_config = /etc/spectrum2/backend-logging.cfg

[database]
# Database backend type
# "sqlite3", "mysql", "pqxx", or "none" without database backend
type = sqlite3

# For SQLite3: Full path to database
# For MySQL and PostgreSQL: name of database
# default database = /var/lib/spectrum2/$jid/database.sql
#database = jabber_transport

# Server.
#server = localhost

# Port.
#port = 0

# User.
#user = spectrum

# Paasword.
#password = secret

# Prefix used for tables
#prefix = jabber_

# Connection string (for pqxx only!)
# If you set this, it ignores every other database option except for type and prefix.
#connectionstring = host=localhost user=specturm password=secret

[registration]
# Enable public registrations
enable_public_registration=1

# Text to display upon user registration form
#username_label=Jabber JID (e.g. user@server.tld):
#instructions=Enter your remote jabber JID and password as well as your local username and password

# If True a local jabber account on <local_account_server> is needed
# for transport registration, the idea is to enable public registration
# from other servers, but only for users, who have already local accounts
#require_local_account=1
#local_username_label=Local username (without @server.tld):
#local_account_server=localhost
#local_account_server_timeout=10000
```

**Comment by vitalyster** [comment]
This error message is produced by libpurple when it doesn't find appropriate protocol library in desired directory. You can see purple log in backend.log file and the most common issue is - you have place prpl-facebook.so in different path. Check the log and place it in the right place

**Comment by QomariSanjaya** [comment]
this is i got from the log, is this mean something? As i really newbie on this
2679: 2017-05-15 11:29:40,737 INFO  libpurple: nss:TLS supported versions: 0x0300 through 0x0303
2679: 2017-05-15 11:29:40,737 INFO  libpurple: nss:TLS versions allowed by default: 0x0301 through 0x0303
2679: 2017-05-15 11:29:40,737 INFO  libpurple: certificate:CertificateScheme x509 requested but not found.
2679: 2017-05-15 11:29:40,737 INFO  libpurple: certificate:CertificateScheme x509 registered
2679: 2017-05-15 11:29:40,737 INFO  libpurple: util:Reading file smileys.xml from directory /var/lib/spectrum2/facebook.fb.fortunecells.xyz
2679: 2017-05-15 11:29:40,737 INFO  libpurple: util:File /var/lib/spectrum2/facebook.fb.fortunecells.xyz/smileys.xml does not exist (this is not necessarily an error)
2679: 2017-05-15 11:29:40,737 INFO  libpurple: stun:using server
2679: 2017-05-15 11:29:40,737 INFO  libpurple: util:Reading file blist.xml from directory /var/lib/spectrum2/facebook.fb.fortunecells.xyz
2679: 2017-05-15 11:29:40,737 INFO  libpurple: util:File /var/lib/spectrum2/facebook.fb.fortunecells.xyz/blist.xml does not exist (this is not necessarily an error)
2679: 2017-05-15 11:29:40,737 INFO  libpurple: prefs:Reading /var/lib/spectrum2/facebook.fb.fortunecells.xyz/prefs.xml
2679: 2017-05-15 11:29:40,738 INFO  libpurple: prefs:/plugins/core/nss_prefs/cipher_list changed, scheduling save.
2679: 2017-05-15 11:29:40,738 INFO  libpurple: prefs:Finished reading /var/lib/spectrum2/facebook.fb.fortunecells.xyz/prefs.xml
2679: 2017-05-15 11:29:40,893 INFO  backend: fortunecells: Invalid protocol 'prpl-facebook'
2679: 2017-05-15 11:29:46,203 INFO  libpurple: util:Writing file prefs.xml to directory /var/lib/spectrum2/facebook.fb.fortunecells.xyz
2679: 2017-05-15 11:29:46,203 INFO  libpurple: util:Writing file /var/lib/spectrum2/facebook.fb.fortunecells.xyz/prefs.xml
2679: 2017-05-15 11:29:52,821 INFO  backend: Exiting...`

**Comment by vitalyster** [comment]
look a few lines before - there should be lines like `plugins: probing ...` where `...` starts with path to plugins location, and there must be your prpl-facebook.so

**Comment by QomariSanjaya** [comment]
I check there is no probing to prpl-facebook.so, there are just probing to like this
`2675: 2017-05-15 11:29:19,815 INFO  backend: Setting libpurple plugins directory to: ./plugins
2675: 2017-05-15 11:29:19,815 INFO  backend: Setting libpurple cacerts directory to: ./ca-certs
2675: 2017-05-15 11:29:19,815 INFO  backend: Setting libpurple user directory to: /var/lib/spectrum2/facebook.fb.fortunecells.xyz
2675: 2017-05-15 11:29:19,815 INFO  backend: Will use glib based event loop
2675: 2017-05-15 11:29:19,816 INFO  libpurple: prefs:Reading /var/lib/spectrum2/facebook.fb.fortunecells.xyz/prefs.xml
2675: 2017-05-15 11:29:19,816 INFO  libpurple: prefs:Finished reading /var/lib/spectrum2/facebook.fb.fortunecells.xyz/prefs.xml
2675: 2017-05-15 11:29:19,816 INFO  libpurple: dbus:Failed to get connection: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
2675: 2017-05-15 11:29:19,816 INFO  libpurple: plugins:probing /usr/lib/purple-2/libjabber.so
2675: 2017-05-15 11:29:19,820 INFO  libpurple: plugins:/usr/lib/purple-2/libjabber.so is not usable because the 'purple_init_plugin' symbol could not be found.  Does the plugin call the PURPLE_INI$
2675: 2017-05-15 11:29:19,820 INFO  libpurple: plugins:probing /usr/lib/purple-2/libicq.so
2675: 2017-05-15 11:29:19,830 INFO  libpurple: plugins:probing /usr/lib/purple-2/libnovell.so
2675: 2017-05-15 11:29:19,837 INFO  libpurple: plugins:probing /usr/lib/purple-2/libyahoojp.so
2675: 2017-05-15 11:29:19,845 INFO  libpurple: plugins:probing /usr/lib/purple-2/statenotify.so
2675: 2017-05-15 11:29:19,845 INFO  libpurple: plugins:probing /usr/lib/purple-2/nss-prefs.so
2675: 2017-05-15 11:29:19,875 INFO  libpurple: plugins:probing /usr/lib/purple-2/libsametime.so
2675: 2017-05-15 11:29:19,891 INFO  libpurple: plugins:/usr/lib/purple-2/libsametime.so has a prefs_info, but is a prpl. This is no longer supported.
2675: 2017-05-15 11:29:19,891 INFO  libpurple: plugins:probing /usr/lib/purple-2/ssl.so
2675: 2017-05-15 11:29:19,891 INFO  libpurple: plugins:probing /usr/lib/purple-2/liboscar.so
2675: 2017-05-15 11:29:19,892 INFO  libpurple: plugins:/usr/lib/purple-2/liboscar.so is not usable because the 'purple_init_plugin' symbol could not be found.  Does the plugin call the PURPLE_INIT$
2675: 2017-05-15 11:29:19,892 INFO  libpurple: plugins:probing /usr/lib/purple-2/libaim.so
2675: 2017-05-15 11:29:19,892 INFO  libpurple: plugins:probing /usr/lib/purple-2/perl.so
2675: 2017-05-15 11:29:19,912 INFO  libpurple: plugins:probing /usr/lib/purple-2/autoaccept.so
2675: 2017-05-15 11:29:19,912 INFO  libpurple: plugins:probing /usr/lib/purple-2/libirc.so
2675: 2017-05-15 11:29:19,913 INFO  libpurple: plugins:probing /usr/lib/purple-2/libmxit.so
2675: 2017-05-15 11:29:19,914 INFO  libpurple: prpl-loubserp-mxit:Loading MXit libPurple plugin...
2675: 2017-05-15 11:29:19,914 INFO  libpurple: plugins:probing /usr/lib/purple-2/joinpart.so
2675: 2017-05-15 11:29:19,914 INFO  libpurple: plugins:probing /usr/lib/purple-2/libbonjour.so
2675: 2017-05-15 11:29:19,921 INFO  libpurple: plugins:probing /usr/lib/purple-2/libmsn.so
2675: 2017-05-15 11:29:19,923 INFO  libpurple: plugins:probing /usr/lib/purple-2/ssl-nss.so
2675: 2017-05-15 11:29:19,924 INFO  libpurple: plugins:probing /usr/lib/purple-2/libzephyr.so
2675: 2017-05-15 11:29:19,925 INFO  libpurple: plugins:probing /usr/lib/purple-2/libyahoo.so
2675: 2017-05-15 11:29:19,926 INFO  libpurple: plugins:probing /usr/lib/purple-2/libgg.so
2675: 2017-05-15 11:29:19,926 INFO  libpurple: plugins:probing /usr/lib/purple-2/buddynote.so
2675: 2017-05-15 11:29:19,927 INFO  libpurple: plugins:probing /usr/lib/purple-2/tcl.so
2675: 2017-05-15 11:29:19,960 INFO  libpurple: plugins:probing /usr/lib/purple-2/log_reader.so
2675: 2017-05-15 11:29:19,960 INFO  libpurple: plugins:probing /usr/lib/purple-2/psychic.so
2675: 2017-05-15 11:29:19,960 INFO  libpurple: plugins:probing /usr/lib/purple-2/libmyspace.so
2675: 2017-05-15 11:29:19,960 INFO  libpurple: plugins:probing /usr/lib/purple-2/libxmpp.so
2675: 2017-05-15 11:29:19,961 INFO  libpurple: plugins:probing /usr/lib/purple-2/dbus-example.so
2675: 2017-05-15 11:29:19,961 INFO  libpurple: plugins:probing /usr/lib/purple-2/offlinemsg.so
2675: 2017-05-15 11:29:19,961 INFO  libpurple: plugins:probing /usr/lib/purple-2/idle.so
2675: 2017-05-15 11:29:19,961 INFO  libpurple: plugins:probing /usr/lib/purple-2/libsimple.so
2675: 2017-05-15 11:29:19,961 INFO  libpurple: plugins:probing /usr/lib/purple-2/newline.so
2675: 2017-05-15 11:29:19,961 INFO  libpurple: plugins:probing /usr/lib/purple-2/libymsg.so
`

**Comment by vitalyster** [comment]
so you need to place libfacebook.so into `/usr/lib/purple-2` directory

**Comment by QomariSanjaya** [comment]
Hm,,there is no such file in my system
Btw i install spectrum using this tutorial http://spectrum.im/documentation/installation/packages_debian_ubuntu.html, is this tutorial include facebook in the libpurple_backend?

**Comment by vitalyster** [comment]
no, facebook plugin isn't included in libpurple, it is a third-party library - https://github.com/dequis/purple-facebook
