### ISSUE TITLE
Will there be support for Debian 9 stretch?

### ISSUE THREAD

**Issue by mightyBroccoli** [hanzz/spectrum2#226]
As Debian 9 stretch just released will there be support for it?

**Comment by vitalyster** [comment]
Sorry, we doesn't have enough resources to build packages for all available platforms. You can build it yourself using [official instructions](http://spectrum.im/documentation/installation/packages_debian_ubuntu.html)

**Comment by mightyBroccoli** [comment]
I am confused Debian Jessie was the latest LTS from Debian until today. Is there no intention to move the project up to use the latest lts of Debian?

**Comment by a13** [comment]
Also you can take a look at build instructions here https://github.com/hanzz/spectrum2/issues/83
