### ISSUE TITLE
Facebook Unknown HTTP error

### ISSUE THREAD

**Issue by QomariSanjaya** [hanzz/spectrum2#229]
Why i sometimes got this message: Unknown HTTP error
After that the facebook transport doesnt work again and need to relogin the xmpp account

**Comment by vitalyster** [comment]
https://github.com/dequis/purple-facebook/issues

**Comment by mightyBroccoli** [comment]
dequis/purple-facebook/issues/332
in the repo for the plugin there is already a thread going about this. This problem is reoccurring all the time since this plugin is reverse engineering the fb messenger protocol.

**Comment by dequis** [comment]
>This problem is reoccurring all the time since this plugin is reverse engineering the fb messenger protocol.

No, it's not. The only reason it's "reoccurring" is that people fail to upgrade to the latest version.

**Comment by mightyBroccoli** [comment]
@dequis Ok I am sorry, I did not know that. It just keeps reappearing in the issues that I thought its a reoccurring problem :D 
Sorry man ...
