### ISSUE TITLE
Debian init script

### ISSUE THREAD

**Issue by vitalyster** [hanzz/spectrum2#55]
We don't have one

**Comment by stv0g** [comment]
There's one at: [packaging/fedora/spectrum2.init](../tree/master/packaging/fedora/spectrum2.init) which can be easily adapted to Debian's style.

But a systemd service is missing though.

**Comment by cptMikky** [comment]
I made a LSB-ish init script compatible with Debian and a systemd unit file:

Init script (/etc/init.d/spectrum2): http://pastebin.com/MUMN5X9L
systemd unit (/lib/systemd/system/spectrum2.service): http://pastebin.com/UYJ5bfqv

**Comment by vitalyster** [comment]
@cptMikky thanks, commited as 6023bfed11eeb66cc207054c
