### ISSUE TITLE
Drop old skype backend in favor of prpl-skypeweb

### ISSUE THREAD

**Issue by vitalyster** [hanzz/spectrum2#56]
It does not needed anymore

**Comment by stv0g** [comment]
:+1: We should really drop those outdated dependencies. Focusing on libpurple makes sense to me.

**Comment by cypa** [comment]
WTF!!!
guys, do it right now! I've lost few days debugging skype backend before I realized MS dropped skype-desktop-API ... 
and place WARNING! to skype-backend documentation pages!!!

**Comment by vitalyster** [comment]
fixed in 247e51a194cb
