### ISSUE TITLE
libpurple backend: request_input_* mapping to xmpp

### ISSUE THREAD

**Issue by vitalyster** [hanzz/spectrum2#62]
Some libpurple plugins (e.g. steamworks) requesting user input (steam guard code in this case) but it is not forwarded to spectrum user.

**Comment by vitalyster** [comment]
https://github.com/EionRobb/pidgin-opensteamworks/issues/69

**Comment by theWeird** [comment]
+1 for steam guard inputs

**Comment by Pacien** [comment]
The telegram-purple plugin opens a virtual conversation in order to ask the user for the auth code as a fallback:

https://github.com/majn/telegram-purple/blob/4ef719cd3a55375114864c86a1df6238955c39cf/tgp-request.c#L58

**Comment by thfree** [comment]
+1, очень хотелось бы данный функционал.
