### ISSUE TITLE
Use Boost.Signals2 instead of Boost.Signals

### ISSUE THREAD

**Issue by stv0g** [hanzz/spectrum2#63]
`libtransport` still uses the old and deprecated `boost::signal` classes:

```
"Boost.Signals is no longer being maintained and is now deprecated. Please switch to Boost.Signals2. To disable this warning message, define BOOST_SIGNALS_NO_DEPRECATION_WARNING."
```

A porting guide to the new `boost::signals2` system is available here: http://www.boost.org/doc/libs/1_59_0/doc/html/signals2/api_changes.html#signals2.porting

Unfortunately, Swiften is also still using the old `boost::signal`

**Comment by vitalyster** [comment]
Fixed in https://github.com/hanzz/spectrum2/commit/6d2f8c1927613d87b5872b75601d211fe68dadb3
