### ISSUE TITLE
Telegram and OAuth authorization

### ISSUE THREAD

**Issue by mcepl** [hanzz/spectrum2#67]
a) Telegram uses OAuth, so there is no password
b) I expect to enter only my phone number (in +420..... full size format) and to get SMS to the phone with a code which I enter to the message tab opened in my chat program.

**Comment by vitalyster** [comment]
#61 related issue

**Comment by mcepl** [comment]
OK, I got the confirmation SMS with a long long delay (which may be a problem of Telegram, they have incredible delays these days), but I don't seem to be able to sent it back. When trying to send the code to the transport contact, gajim shows me the red icon ("This code indicates that the message has not been sent yet ...").

**Comment by black-roland** [comment]
As a workaround you can authenticate using Pidgin and copy `telegram-purple` directory to the spectrum server (`/var/lib/spectrum2/<component_name>/telegram-purple`).

**Comment by mcepl** [comment]
Yup, works for me. So, aside from botched registration we have working Telegram transport (except, Telegram as such is not working much for me ;)).

**Comment by hanzz** [comment]
We can use "compat-verification" feature in purple-telegram, but it is broken currently. I've submitted PR to fix it: https://github.com/majn/telegram-purple/pull/183. Once this gets merged, I will update our Docker image and it should just start working.

**Comment by hanzz** [comment]
Check the discussion for https://github.com/majn/telegram-purple/pull/183 for information on prpl-telegram side. From Spectrum 2 side, I consider this fixed.
