### ISSUE TITLE
Different "frontend" protocols

### ISSUE THREAD

**Issue by vitalyster** [hanzz/spectrum2#69]
As XMPP popularity not growing fast now, we can provide ability to use different client side protocols: some examples of suitable open protocols - IRC, SIP, [Matrix protocol](http://matrix.org/docs/spec/). Also some proprietary protocols allow third-party extensions, e.g. [Slack](https://api.slack.com/)
It can attract more users and developers to spectrum, and these protocols have more stable and feature-rich clients and libraries, e.g. it is much simpler to add voip capability with existing SIP/WebRTC library than with dated XMPP specs and clients

**Comment by hanzz** [comment]
Do you personally use any of these? I definitely think it's good idea, but so far I don't have any knowledge of these networks and I probably don't want to try implementing something for all of them, so we should decide which one we should try as first.

I would like to choose some where the Spectrum would be more useful, but for now I have no idea which one would it be.

I don't mind adding support for proprietary protocols which allows third-party extension. Having Slack to support some of our features looks quite good.

**Comment by vitalyster** [comment]
At first we can provide generic API for writing different "frontend" :)

**Comment by hanzz** [comment]
I'm not sure I'll be able to write generic API without really trying to use it for some frontend :)

**Comment by vitalyster** [comment]
fixed in 2.0 :)
