### ISSUE TITLE
Packages for Debian Jessie

### ISSUE THREAD

**Issue by SebastianS90** [hanzz/spectrum2#70]
Is it possible to provide packages for the current debian stable release (Jessie)?

The wheezy packages depend on some libboost-* library packages that are no longer available in jessie (probably because of a version upgrade and new package name). It is possible to add a wheezy apt sources entry to install the required old dependencies, but then you have a mixture of different debian releases which is generally not recommended.

**Comment by vitalyster** [comment]
Now you can find `build_spectrum2.sh` in `packaging/debian` directory, and it will build packages for you.
You may also need to build `libcommuni` packages, now they are available in https://github.com/vitalyster/libcommuni-gbp.git (just run `gbp buildpackage` in repository root)

**Comment by SebastianS90** [comment]
Thanks. Are there any plans to push binary packages to http://repo.spectrum.im/? (this repo is linked in the download instructions on spectrum.im)

**Comment by vitalyster** [comment]
Repo will be updated when spectrum2 will be released, at now we have no maintainers for "nightly package builds"

**Comment by moyamo** [comment]
The script is currently broken. Here's a patch to fix it:
```
diff --git a/packaging/debian/build_spectrum2.sh b/packaging/debian/build_spectrum2.sh
index b90c31d..7e95467 100755
--- a/packaging/debian/build_spectrum2.sh
+++ b/packaging/debian/build_spectrum2.sh
@@ -17,11 +17,17 @@ rm -rf spectrum2_*

 git clone ../../.git spectrum2-$version

+cd spectrum2-$version
+sed -i '3ienable_testing()' CMakeLists.txt
+cd ..
+
 tar -czf spectrum2_$version.orig.tar.gz spectrum2-$version

 cp -r debian spectrum2-$version/debian

 cd spectrum2-$version
+
+
 debuild -i -us -uc

 cd ..
diff --git a/packaging/debian/debian/changelog b/packaging/debian/debian/changelog
index 987597c..e6e439f 100644
--- a/packaging/debian/debian/changelog
+++ b/packaging/debian/debian/changelog
@@ -1,4 +1,4 @@
-spectrum2 (1:1760-89e377b-1) unstable; urgency=low
+spectrum2 (1:1882-61f2419-1) unstable; urgency=low

   * Move package to git-buildpackage format
   * remove the -git suffix from package names
diff --git a/packaging/debian/debian/control b/packaging/debian/debian/control
index e8860c7..452e184 100644
--- a/packaging/debian/debian/control
+++ b/packaging/debian/debian/control
@@ -6,7 +6,7 @@ Build-Depends: debhelper (>= 7.0.50~), libpurple-dev, libswiften-dev,
  libprotobuf-dev, libmysqlclient-dev, liblog4cxx10-dev, protobuf-compiler,
  libpopt-dev, libdbus-glib-1-dev, libpqxx3-dev, cmake, libevent-dev, libboost-all-dev,
  libqt4-dev, libidn11-dev, libxml2-dev, libavahi-client-dev, libavahi-common-dev,
- libcurl4-openssl-dev, libcommuni-dev
+ libcurl4-openssl-dev, libcommuni-dev, libsqlite3-dev
 Standards-Version: 3.9.2
 VCS-Browser: http://git.fsinf.at/apt/spectrum2
 VCS-Git: https://git.fsinf.at/apt/spectrum2.git
```

**Comment by jkufner** [comment]
Please note this problem also includes libswiften, which also depends on outdated libboost.

**Comment by vitalyster** [comment]
http://spectrum.im/documentation/installation/packages_debian_ubuntu.html

**Comment by jkufner** [comment]
Are there also packages for i386 or is it amd64 only?

**Comment by jkufner** [comment]
@vitalyster Thank you for setting up the repo!

**Comment by vitalyster** [comment]
No time to build all possible distributions/architectures, maintainers welcome :)

**Comment by thundergreen** [comment]
ARMHF Packages :)
