### ISSUE TITLE
How to compile this source code, as i am beginner.

### ISSUE THREAD

**Issue by genesis231** [hanzz/spectrum2#71]

**Comment by vitalyster** [comment]
Please follow documentation - http://spectrum.im/documentation/

**Comment by genesis231** [comment]
i think that documentation is for old version of spectrum. How to compile new version. I am confused with dockerfile.

**Comment by vitalyster** [comment]
Well, read this or I will close this issue - http://www.chiark.greenend.org.uk/~sgtatham/bugs.html
