### ISSUE TITLE
Error while compiling 

### ISSUE THREAD

**Issue by genesis231** [hanzz/spectrum2#75]
[ 43%] Building CXX object src/CMakeFiles/transport.dir/__/include/Swiften/TLS/OpenSSL/OpenSSLServerContextFactory.cpp.o
[ 43%] Building CXX object src/CMakeFiles/transport.dir/__/include/Swiften/StreamStack/TLSServerLayer.cpp.o
Linking CXX shared library libtransport.so
/usr/bin/ld: /usr/local/lib/libpqxx.a(connection_base.o): relocation R_X86_64_32 against `_ZN4pqxx17broken_connectionD1Ev' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpqxx.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/CMakeFiles/transport.dir/build.make:1727: recipe for target 'src/libtransport.so.2.0' failed
make[2]: *** [src/libtransport.so.2.0] Error 1
CMakeFiles/Makefile2:76: recipe for target 'src/CMakeFiles/transport.dir/all' failed
make[1]: *** [src/CMakeFiles/transport.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by moyamo** [comment]
What Operating system are you using?

**Comment by genesis231** [comment]
ubuntu kylin

**Comment by moyamo** [comment]
#74 Shows that `popt` is missing. Try installing `libpopt-dev`

    apt-get install libpopt-dev

Then rerun `cmake` and try compiling again.

**Comment by genesis231** [comment]
already installed

**Comment by moyamo** [comment]
`grep` through the `Makefiles` for `CXXFLAGS`. Then add `-fPIC` on the line that contains `CXXFLAGS` and see if that makes a difference.

**Comment by genesis231** [comment]
accept my invitation, i wanna talk

**Comment by hanzz** [comment]
Why did you install libpqxx from the source code? it exists in Ubuntu repository:

http://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=pqxx-dev&searchon=names

Also, you could consider using Docker image instead of compiling it.

http://spectrum.im/documentation/installation/docker.html
