### ISSUE TITLE
User statuses and profile pictures not working/unsupported with WhatsApp-Purple

### ISSUE THREAD

**Issue by dariox86** [hanzz/spectrum2#77]
I have successfully set up my instance of Spectrum 2 with WhatsApp-Purple, though profile pictures and user statuses do not seem to work. Is it just me or they are yet to be implemented?

**Comment by vitalyster** [comment]
whatsapp-purple known to be buggy, try https://github.com/stv0g/transwhat instead

**Comment by dariox86** [comment]
I did. These features are not supported as well: https://github.com/stv0g/transwhat/issues/21

**Comment by dariox86** [comment]
Even if it is buggy, I would stick with Spectrum 2 + WhatsApp-Purple if those features are supported.
