### ISSUE TITLE
Add support for case-sensitive buddy-names

### ISSUE THREAD

**Issue by majn** [hanzz/spectrum2#86]
I'm the developer of the libpurple plugin [telegram-purple](https://github.com/majn/telegram-purple) you currently suggest for getting Telegram to work in Spectrum 2. Due to some changes in how usernames are handled since v.1.2.2 (case sensitive human-readable names), Spectrum will most likely no longer work in version >=1.2.2 cause it lowercases all user names.

I will not be able to implement a workaround for spectrum, since introducing case insensitivity at this point would mean breaking backwards compatibility to existing buddy lists and histories. You can still use v1.2.1 for spectrum, but I have limited time and will no longer fix any bugs for this version in case they occur.

It would probably be a good idea to provide a native telegram plugin for Spectrum in case you intend to support it any further. The library [libtgl](https://github.com/vysheng/tgl) should make the implementation rather easy. You can look at telegram-purples or telegram-cli's source code to learn how to use the library, and I will also offer my help in case there are any questions about libtgl or Telegram.

**Comment by hanzz** [comment]
Thanks for the info, but I'm not sure why this shouldn't work. We can forward any username to XMPP and back and node part of XMPP JID is case sensitive, so it should not be a problem :). If there's a bug in Spectrum making the node part of JID lower-case I will fix it.

**Comment by majn** [comment]
I dont run any instance of spectrum to test it, I was basing this on bug reports and logs I've received.

 /var/log/spectrum2/telegram.*****.*****/backends/backend-1.log 

    649897: 2015-12-25 23:03:37,836 INFO  libpurple: prpl-telegram:tgprpl_send_im()
    649897: 2015-12-25 23:03:37,836 INFO  libpurple: prpl-telegram:who=matthias jentsch
    649897: 2015-12-25 23:03:37,836 ERROR backend: g_log (tgp-blist.c:45):tgp_blist_peer_find: code should not be reached
    649897: 2015-12-25 23:03:37,836 INFO  libpurple: prpl-telegram:peer not found
    649897: 2015-12-25 23:03:37,836 INFO  backend: MSG

The variable passed to send_im should be have been "Matthias Jentsch" instead of "matthias jentsch". 


/var/log/spectrum2/telegram.******.******/spectrum2.log

      2015-12-25 23:03:37,835 INFO  Component.RAW: RAW DATA IN <message   to='matthias\20jentsch@telegram.******.******' id='af74a' type='chat' from='*****@*****.*****/Xxxx'>
      <body>not working</body>
      <active xmlns='http://jabber.org/protocol/chatstates'/>
      <request xmlns='urn:xmpp:receipts'/>
      </message>

**Comment by hanzz** [comment]
How does adding new contacts work now in 1.3.0? Do you expect users to put the name of the contact to "Buddy's username" field in the Pidgin dialog?

**Comment by vitalyster** [comment]
Does telegram expose some kind of user ids? May it be the key for using in "buddy lists and histories"? Does libpurple have different field to store human-readable username? Why not use it? :)

**Comment by majn** [comment]
> Does telegram expose some kind of user ids? May it be the key for using in "buddy lists and histories"?
  
Telegram has some internal UID, but its not useful to display it to the user for the following reasons:
1. No other Telegram client exposes that ID, its an alien concept to people that use Telegram
2. you can't use just the ID to do the RPC operations, since you would also need some 128(?) bit access hash that is associated with it. So ironically, by knowing just the UID you will not be able to fetch user info or add a user to the contact list.

>Does libpurple have different field to store human-readable username? Why not use it? :)

Libpurple has two major attributes that define a users name: "name" and "alias". 
- "name" is the unique non-changing name of the user, which the user needs to specify when creating a new conversation, or searching for history. 
- "alias" can be specified for each buddy list entry to override the name. Its mostly used for user-defined nick-names.

I could use the ID as "name" and the name as "Alias" but this causes the following problems:
- When just an ID shows up, the user will not be able to associate it with somebody.
- The alias resolution only works when there's a buddy list entry. Telegram can have huge Multi-User-Chats with 100s and I can't add all of those to the users buddy list just to get all those names to work.
- Telegram has the concept of foreign users you can chat with that aren't on the blist, which I would have to add to the blist too

And this is still just the tip of the iceberg ... 


> How does adding new contacts work now in 1.3.0? Do you expect users to put the name of the contact to "Buddy's username" field in the Pidgin dialog?

Its not possible right now. Adding new contacts in Telegram works by executing a text search on the user's name, which will then deliver the user ID+Access Hash that the prpl can use to add those users.

**Comment by hanzz** [comment]
Thanks for the answers. I think it all make sense now.

**Comment by hanzz** [comment]
I think it should be possible for Spectrum to map lower-cased XMPP JID to the proper case-sensitive buddy name. We won't be able to add new buddies from XMPP side to telegram, but that probably does not work right now too...

**Comment by majn** [comment]
Btw, my current development branch is https://github.com/majn/telegram-purple/tree/dev-1.2.3, if you do some testing, please do it on that one. 

1.3.0 still has many issues.

**Comment by homocogitum** [comment]
the bug still exists.

**Comment by hanzz** [comment]
Try to unregister the transport and register it again please.

**Comment by homocogitum** [comment]
Yes, it worked. but I have found other bug - can't send messages to users with cyryllic Nicknames.

**Comment by hanzz** [comment]
Do you have log from that? Try to disconnect from XMPP, connect again, write message to someone with cyrylic nicknames and send what appeared in the log.

**Comment by majn** [comment]
I've had issues like that that were caused by non-equality of composed/decomposed normalization formats in standard C string comparison functions.

I always try to normalize all strings to composed format in telegram-purple to avoid this issue.

**Comment by homocogitum** [comment]
Here is the log:
42370: 2016-01-23 17:01:58,582 INFO  libpurple: prpl-telegram:tgprpl_send_typing()
42370: 2016-01-23 17:01:58,582 ERROR backend: g_log tgp_blist_lookup_peer_get: assertion 'id' failed
42370: 2016-01-23 17:01:58,622 INFO  libpurple: prpl-telegram:tgprpl_send_im()
42370: 2016-01-23 17:01:58,622 ERROR backend: g_log tgp_blist_lookup_peer_get: assertion 'id' failed
42370: 2016-01-23 17:01:58,622 INFO  libpurple: prpl-telegram:peer not found
42370: 2016-01-23 17:01:58,623 INFO  backend: MSG

**Comment by hanzz** [comment]
Can you try with the latest version and send the backend log again? You should see output like:

```
Sending message to 'Firstname Surname'.
```

Also, does it work for you in Pidgin with the same version of purple-telegram? So far, according to spectrum2.log, it seems we are using proper PurpleBuddy name in your case...

**Comment by hanzz** [comment]
@majn: I believe it should not be that problem on my side. Spectrum 2 can have problem like that - it could probably not find the right internal buddy structure without the normalization, but it still forwards the message to purple-telegram with the right utf8 name.

Would you mind to commit some kind of debugging of this problem temporarily so @homocogitum can test it?

**Comment by homocogitum** [comment]
@hanzz everything works fine in Pidgin.
Here is new log:
3000: 2016-01-23 21:01:47,727 INFO  libpurple: prpl-telegram:tgprpl_send_typing()
3000: 2016-01-23 21:01:47,727 ERROR backend: g_log tgp_blist_lookup_peer_get: assertion 'id' failed
3000: 2016-01-23 21:01:47,766 INFO  backend: Sending message to '???????? ????????????????'
3000: 2016-01-23 21:01:47,766 INFO  libpurple: prpl-telegram:tgprpl_send_im()
3000: 2016-01-23 21:01:47,766 ERROR backend: g_log tgp_blist_lookup_peer_get: assertion 'id' failed
3000: 2016-01-23 21:01:47,766 INFO  libpurple: prpl-telegram:peer not found
3000: 2016-01-23 21:01:47,766 INFO  backend: MSG
It seems that something is wrong with "Firstname Surname". Instead of every character there are ??. Two '?' characters instead of every letter (and spaces).

**Comment by majn** [comment]
Hmm, the warnings in the log already allow me to reconstruct whats happening. 

A user name is passed to tgprpl_send_im, but its not yet known to telegram-purple. Since the lookup is doing a normalization this is probably not the problem. Apply the following patch onto telegram-purple 1.2.4 with git apply:

    git apply tgp.diff.txt 

[tgp.diff.txt](https://github.com/hanzz/spectrum2/files/101994/tgp.diff.txt)

**Comment by majn** [comment]
To clarify, this should print additional debugging information, NOT fix the issue.

**Comment by homocogitum** [comment]
Here is new log: 
65911: 2016-01-23 21:50:02,498 INFO  libpurple: prpl-telegram:tgprpl_send_typing()
65911: 2016-01-23 21:50:02,498 ERROR backend: g_log tgp_blist_lookup_peer_get: assertion 'id' failed
65911: 2016-01-23 21:50:02,538 INFO  backend: Sending message to '???????? ????????????????'
65911: 2016-01-23 21:50:02,538 INFO  libpurple: prpl-telegram:tgprpl_send_im()
65911: 2016-01-23 21:50:02,538 INFO  libpurple: prpl-telegram:who=???????? ????????????????
65911: 2016-01-23 21:50:02,538 INFO  libpurple: prpl-telegram:ffffffd0
65911: 2016-01-23 21:50:02,538 INFO  libpurple: prpl-telegram:ffffffba
65911: 2016-01-23 21:50:02,538 INFO  libpurple: prpl-telegram:ffffffd0
65911: 2016-01-23 21:50:02,538 INFO  libpurple: prpl-telegram:ffffffb0
65911: 2016-01-23 21:50:02,538 INFO  libpurple: prpl-telegram:ffffffd1
65911: 2016-01-23 21:50:02,538 INFO  libpurple: prpl-telegram:ffffff82
65911: 2016-01-23 21:50:02,538 INFO  libpurple: prpl-telegram:ffffffd1
65911: 2016-01-23 21:50:02,538 INFO  libpurple: prpl-telegram:ffffff8f
65911: 2016-01-23 21:50:02,538 INFO  libpurple: prpl-telegram:20
65911: 2016-01-23 21:50:02,538 INFO  libpurple: prpl-telegram:ffffffd0
65911: 2016-01-23 21:50:02,538 INFO  libpurple: prpl-telegram:ffffffb0
65911: 2016-01-23 21:50:02,538 INFO  libpurple: prpl-telegram:ffffffd0
65911: 2016-01-23 21:50:02,538 INFO  libpurple: prpl-telegram:ffffffbd
65911: 2016-01-23 21:50:02,538 INFO  libpurple: prpl-telegram:ffffffd1
65911: 2016-01-23 21:50:02,538 INFO  libpurple: prpl-telegram:ffffff82
65911: 2016-01-23 21:50:02,538 INFO  libpurple: prpl-telegram:ffffffd0
65911: 2016-01-23 21:50:02,538 INFO  libpurple: prpl-telegram:ffffffbe
65911: 2016-01-23 21:50:02,538 INFO  libpurple: prpl-telegram:ffffffd0
65911: 2016-01-23 21:50:02,538 INFO  libpurple: prpl-telegram:ffffffbd
65911: 2016-01-23 21:50:02,538 INFO  libpurple: prpl-telegram:ffffffd0
65911: 2016-01-23 21:50:02,538 INFO  libpurple: prpl-telegram:ffffffbe
65911: 2016-01-23 21:50:02,538 INFO  libpurple: prpl-telegram:ffffffd0
65911: 2016-01-23 21:50:02,538 INFO  libpurple: prpl-telegram:ffffffb2
65911: 2016-01-23 21:50:02,538 INFO  libpurple: prpl-telegram:ffffffd0
65911: 2016-01-23 21:50:02,538 INFO  libpurple: prpl-telegram:ffffffb0
65911: 2016-01-23 21:50:02,538 ERROR backend: g_log tgp_blist_lookup_peer_get: assertion 'id' failed
65911: 2016-01-23 21:50:02,538 INFO  libpurple: prpl-telegram:peer not found
65911: 2016-01-23 21:50:02,538 INFO  backend: MSG

**Comment by hanzz** [comment]
Just for info, the name should be "катя антонова".

**Comment by majn** [comment]
That string actually contains that name but whatever terminal or text editor you are using can't display them.

**Comment by hanzz** [comment]
@majn, could you dump what's in that ghash? That contact should be there... :(

**Comment by majn** [comment]
Give me a second.

**Comment by hanzz** [comment]
In Pidgin, the debug output is following:
```
(22:10:16) prpl-telegram: ffffffd0
(22:10:16) prpl-telegram: ffffff9a
(22:10:16) prpl-telegram: ffffffd0
(22:10:16) prpl-telegram: ffffffb0
(22:10:16) prpl-telegram: ffffffd1
(22:10:16) prpl-telegram: ffffff82
(22:10:16) prpl-telegram: ffffffd1
(22:10:16) prpl-telegram: ffffff8f
(22:10:16) prpl-telegram: 20
(22:10:16) prpl-telegram: ffffffd0
(22:10:16) prpl-telegram: ffffff90
(22:10:16) prpl-telegram: ffffffd0
(22:10:16) prpl-telegram: ffffffbd
(22:10:16) prpl-telegram: ffffffd1
(22:10:16) prpl-telegram: ffffff82
(22:10:16) prpl-telegram: ffffffd0
(22:10:16) prpl-telegram: ffffffbe
(22:10:16) prpl-telegram: ffffffd0
(22:10:16) prpl-telegram: ffffffbd
(22:10:16) prpl-telegram: ffffffd0
(22:10:16) prpl-telegram: ffffffbe
(22:10:16) prpl-telegram: ffffffd0
(22:10:16) prpl-telegram: ffffffb2
(22:10:16) prpl-telegram: ffffffd0
(22:10:16) prpl-telegram: ffffffb0
```

So it seems in the end it's my problem. I need utf8 aware tolower method :) Sorry to waste your time @majn.

**Comment by majn** [comment]
Uhm, good that saves us from searching a huge log containing all contact names as binary dump :P

**Comment by homocogitum** [comment]
Yes, it's working now.

**Comment by hanzz** [comment]
Great, thanks both of you :).

**Comment by demon-ru** [comment]
> Telegram has the concept of foreign users you can chat with that aren't on the blist, which I would have to add to the blist too

How can I send message to users aren't on the blist? When sending a message is searched with buddies (tgp_blist_lookup_peer_get: assertion `id' failed)
Telegram has "username" (unique) and "first name, last name" (not unique). Why the choice was made not in favor of username?
There are some prospects that messaging with any username will work?
Thanks.
