### ISSUE TITLE
404 in docs

### ISSUE THREAD

**Issue by singpolyma** [hanzz/spectrum2#94]
Link on how to register goes to http://spectrum.im/documentation/user_xmpp/register.html which 404s

**Comment by rigid** [comment]
same for http://spectrum.im/documentation/user_xmpp/join_muc.html

**Comment by dahabakuk** [comment]
also here: http://spectrum.im/documentation/tutorials/gateway_mode.html the backend links to github.io

and http://spectrum.im/discussion/ -> click here leads to a 404 -> https://slack.spectrum.imchat/
