### ISSUE TITLE
libpurple backend: not working correctly with libpurple plugins with sms code authorization (like telegram-purple)

### ISSUE THREAD

**Issue by homocogitum** [hanzz/spectrum2#97]
It seems that spectrum2 can't handle correctly authorization in plugins such as telegram-purple, when you log in using your phone number and then you need to enter sms code. Sms code is received, but entering it in transport's chat gives nothing.
Tried only with telegram-purple plugin, but I think that if it doesn't work in this plugin, it won't work in similar plugins.
May be some function of libpurple is not supported properly? telegram-purple works fine in pidgin.

**Comment by hanzz** [comment]
From where did you get telegram purple? You need to have right telegram-purple version:

https://github.com/majn/telegram-purple/pull/183

Or just use our Docker image.

**Comment by thundergreen** [comment]
@HanzZ I'm using the right telegram purple.will provide some logs later but I guess I was the reason why people talk about this issue as I was wondering if someone already git this running

**Comment by homocogitum** [comment]
Works with later version of spectrum2.

**Comment by thundergreen** [comment]
@homocogitum means it is generally broken at this time? then i'll wait. i will add 
[purple]
compat-verification=true

in my telegram cfg.

**Comment by hanzz** [comment]
You don't have to set it, we set that by default in spectrum
